package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Biotype generated by MyEclipse - Hibernate Tools
 */

public class Biotype  implements java.io.Serializable {


    // Fields    

     private Integer biotypeId;
     private String name;
     private Set individualBiotypes = new HashSet(0);
     private Set stocksForMaternalBiotypeId = new HashSet(0);
     private Set biotypePhenotypes = new HashSet(0);
     private Set stocksForBiotypeId = new HashSet(0);
     private Set biotypeOrganisms = new HashSet(0);
     private Set stocksForPaternalBiotypeId = new HashSet(0);


    // Constructors

    /** default constructor */
    public Biotype() {
    }

	/** minimal constructor */
    public Biotype(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Biotype(String name, Set individualBiotypes, Set stocksForMaternalBiotypeId, Set biotypePhenotypes, Set stocksForBiotypeId, Set biotypeOrganisms, Set stocksForPaternalBiotypeId) {
        this.name = name;
        this.individualBiotypes = individualBiotypes;
        this.stocksForMaternalBiotypeId = stocksForMaternalBiotypeId;
        this.biotypePhenotypes = biotypePhenotypes;
        this.stocksForBiotypeId = stocksForBiotypeId;
        this.biotypeOrganisms = biotypeOrganisms;
        this.stocksForPaternalBiotypeId = stocksForPaternalBiotypeId;
    }

   
    // Property accessors

    public Integer getBiotypeId() {
        return this.biotypeId;
    }
    
    public void setBiotypeId(Integer biotypeId) {
        this.biotypeId = biotypeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getIndividualBiotypes() {
        return this.individualBiotypes;
    }
    
    public void setIndividualBiotypes(Set individualBiotypes) {
        this.individualBiotypes = individualBiotypes;
    }

    public Set getStocksForMaternalBiotypeId() {
        return this.stocksForMaternalBiotypeId;
    }
    
    public void setStocksForMaternalBiotypeId(Set stocksForMaternalBiotypeId) {
        this.stocksForMaternalBiotypeId = stocksForMaternalBiotypeId;
    }

    public Set getBiotypePhenotypes() {
        return this.biotypePhenotypes;
    }
    
    public void setBiotypePhenotypes(Set biotypePhenotypes) {
        this.biotypePhenotypes = biotypePhenotypes;
    }

    public Set getStocksForBiotypeId() {
        return this.stocksForBiotypeId;
    }
    
    public void setStocksForBiotypeId(Set stocksForBiotypeId) {
        this.stocksForBiotypeId = stocksForBiotypeId;
    }

    public Set getBiotypeOrganisms() {
        return this.biotypeOrganisms;
    }
    
    public void setBiotypeOrganisms(Set biotypeOrganisms) {
        this.biotypeOrganisms = biotypeOrganisms;
    }

    public Set getStocksForPaternalBiotypeId() {
        return this.stocksForPaternalBiotypeId;
    }
    
    public void setStocksForPaternalBiotypeId(Set stocksForPaternalBiotypeId) {
        this.stocksForPaternalBiotypeId = stocksForPaternalBiotypeId;
    }
   








}