package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * BiotypePhenotype generated by MyEclipse - Hibernate Tools
 */

public class BiotypePhenotype  implements java.io.Serializable {


    // Fields    

     private Integer biotypePhenotypeId;
     private Contact contact;
     private Ptassay ptassay;
     private Pub pub;
     private Biotype biotype;
     private Phenotype phenotype;
     private Date assayDate;
     private String notes;
     private Set biotypePhenotypeProjects = new HashSet(0);


    // Constructors

    /** default constructor */
    public BiotypePhenotype() {
    }

	/** minimal constructor */
    public BiotypePhenotype(Biotype biotype) {
        this.biotype = biotype;
    }
    
    /** full constructor */
    public BiotypePhenotype(Contact contact, Ptassay ptassay, Pub pub, Biotype biotype, Phenotype phenotype, Date assayDate, String notes, Set biotypePhenotypeProjects) {
        this.contact = contact;
        this.ptassay = ptassay;
        this.pub = pub;
        this.biotype = biotype;
        this.phenotype = phenotype;
        this.assayDate = assayDate;
        this.notes = notes;
        this.biotypePhenotypeProjects = biotypePhenotypeProjects;
    }

   
    // Property accessors

    public Integer getBiotypePhenotypeId() {
        return this.biotypePhenotypeId;
    }
    
    public void setBiotypePhenotypeId(Integer biotypePhenotypeId) {
        this.biotypePhenotypeId = biotypePhenotypeId;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Ptassay getPtassay() {
        return this.ptassay;
    }
    
    public void setPtassay(Ptassay ptassay) {
        this.ptassay = ptassay;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Biotype getBiotype() {
        return this.biotype;
    }
    
    public void setBiotype(Biotype biotype) {
        this.biotype = biotype;
    }

    public Phenotype getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(Phenotype phenotype) {
        this.phenotype = phenotype;
    }

    public Date getAssayDate() {
        return this.assayDate;
    }
    
    public void setAssayDate(Date assayDate) {
        this.assayDate = assayDate;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set getBiotypePhenotypeProjects() {
        return this.biotypePhenotypeProjects;
    }
    
    public void setBiotypePhenotypeProjects(Set biotypePhenotypeProjects) {
        this.biotypePhenotypeProjects = biotypePhenotypeProjects;
    }
   








}