package org.nescent.heliconius.hibernate;



/**
 * BiotypePhenotypeProject generated by MyEclipse - Hibernate Tools
 */

public class BiotypePhenotypeProject  implements java.io.Serializable {


    // Fields    

     private Integer biotypePhenotypeProjectId;
     private BiotypePhenotype biotypePhenotype;
     private Project project;


    // Constructors

    /** default constructor */
    public BiotypePhenotypeProject() {
    }

    
    /** full constructor */
    public BiotypePhenotypeProject(BiotypePhenotype biotypePhenotype, Project project) {
        this.biotypePhenotype = biotypePhenotype;
        this.project = project;
    }

   
    // Property accessors

    public Integer getBiotypePhenotypeProjectId() {
        return this.biotypePhenotypeProjectId;
    }
    
    public void setBiotypePhenotypeProjectId(Integer biotypePhenotypeProjectId) {
        this.biotypePhenotypeProjectId = biotypePhenotypeProjectId;
    }

    public BiotypePhenotype getBiotypePhenotype() {
        return this.biotypePhenotype;
    }
    
    public void setBiotypePhenotype(BiotypePhenotype biotypePhenotype) {
        this.biotypePhenotype = biotypePhenotype;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
   








}