package org.nescent.heliconius.hibernate;



/**
 * ContactRelationship generated by MyEclipse - Hibernate Tools
 */

public class ContactRelationship  implements java.io.Serializable {


    // Fields    

     private Integer contactRelationshipId;
     private Contact contactBySubjectId;
     private Contact contactByObjectId;
     private Cvterm cvterm;


    // Constructors

    /** default constructor */
    public ContactRelationship() {
    }

    
    /** full constructor */
    public ContactRelationship(Contact contactBySubjectId, Contact contactByObjectId, Cvterm cvterm) {
        this.contactBySubjectId = contactBySubjectId;
        this.contactByObjectId = contactByObjectId;
        this.cvterm = cvterm;
    }

   
    // Property accessors

    public Integer getContactRelationshipId() {
        return this.contactRelationshipId;
    }
    
    public void setContactRelationshipId(Integer contactRelationshipId) {
        this.contactRelationshipId = contactRelationshipId;
    }

    public Contact getContactBySubjectId() {
        return this.contactBySubjectId;
    }
    
    public void setContactBySubjectId(Contact contactBySubjectId) {
        this.contactBySubjectId = contactBySubjectId;
    }

    public Contact getContactByObjectId() {
        return this.contactByObjectId;
    }
    
    public void setContactByObjectId(Contact contactByObjectId) {
        this.contactByObjectId = contactByObjectId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }
   








}