package org.nescent.heliconius.hibernate;



/**
 * Crossexperimentprop generated by MyEclipse - Hibernate Tools
 */

public class Crossexperimentprop  implements java.io.Serializable {


    // Fields    

     private Integer crossexperimentpropId;
     private Cvterm cvterm;
     private Crossexperiment crossexperiment;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public Crossexperimentprop() {
    }

	/** minimal constructor */
    public Crossexperimentprop(Cvterm cvterm, Crossexperiment crossexperiment, Integer rank) {
        this.cvterm = cvterm;
        this.crossexperiment = crossexperiment;
        this.rank = rank;
    }
    
    /** full constructor */
    public Crossexperimentprop(Cvterm cvterm, Crossexperiment crossexperiment, String value, Integer rank) {
        this.cvterm = cvterm;
        this.crossexperiment = crossexperiment;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getCrossexperimentpropId() {
        return this.crossexperimentpropId;
    }
    
    public void setCrossexperimentpropId(Integer crossexperimentpropId) {
        this.crossexperimentpropId = crossexperimentpropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Crossexperiment getCrossexperiment() {
        return this.crossexperiment;
    }
    
    public void setCrossexperiment(Crossexperiment crossexperiment) {
        this.crossexperiment = crossexperiment;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}