package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Crossexperiment generated by MyEclipse - Hibernate Tools
 */

public class Crossexperiment  implements java.io.Serializable {


    // Fields    

     private Integer crossexperimentId;
     private Cvterm cvterm;
     private Contact contact;
     private Individual individualByMaleId;
     private Individual individualByFemaleId;
     private Geolocation geolocation;
     private String name;
     private Date expdate;
     private Set individuals = new HashSet(0);
     private Set crossexperimentprops = new HashSet(0);


    // Constructors

    /** default constructor */
    public Crossexperiment() {
    }

	/** minimal constructor */
    public Crossexperiment(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Crossexperiment(Cvterm cvterm, Contact contact, Individual individualByMaleId, Individual individualByFemaleId, Geolocation geolocation, String name, Date expdate, Set individuals, Set crossexperimentprops) {
        this.cvterm = cvterm;
        this.contact = contact;
        this.individualByMaleId = individualByMaleId;
        this.individualByFemaleId = individualByFemaleId;
        this.geolocation = geolocation;
        this.name = name;
        this.expdate = expdate;
        this.individuals = individuals;
        this.crossexperimentprops = crossexperimentprops;
    }

   
    // Property accessors

    public Integer getCrossexperimentId() {
        return this.crossexperimentId;
    }
    
    public void setCrossexperimentId(Integer crossexperimentId) {
        this.crossexperimentId = crossexperimentId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Individual getIndividualByMaleId() {
        return this.individualByMaleId;
    }
    
    public void setIndividualByMaleId(Individual individualByMaleId) {
        this.individualByMaleId = individualByMaleId;
    }

    public Individual getIndividualByFemaleId() {
        return this.individualByFemaleId;
    }
    
    public void setIndividualByFemaleId(Individual individualByFemaleId) {
        this.individualByFemaleId = individualByFemaleId;
    }

    public Geolocation getGeolocation() {
        return this.geolocation;
    }
    
    public void setGeolocation(Geolocation geolocation) {
        this.geolocation = geolocation;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Date getExpdate() {
        return this.expdate;
    }
    
    public void setExpdate(Date expdate) {
        this.expdate = expdate;
    }

    public Set getIndividuals() {
        return this.individuals;
    }
    
    public void setIndividuals(Set individuals) {
        this.individuals = individuals;
    }

    public Set getCrossexperimentprops() {
        return this.crossexperimentprops;
    }
    
    public void setCrossexperimentprops(Set crossexperimentprops) {
        this.crossexperimentprops = crossexperimentprops;
    }
   








}