package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Cv generated by MyEclipse - Hibernate Tools
 */

public class Cv  implements java.io.Serializable {


    // Fields    

     private Integer cvId;
     private String name;
     private String definition;
     private Set cvtermpaths = new HashSet(0);
     private Set cvterms = new HashSet(0);


    // Constructors

    /** default constructor */
    public Cv() {
    }

	/** minimal constructor */
    public Cv(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Cv(String name, String definition, Set cvtermpaths, Set cvterms) {
        this.name = name;
        this.definition = definition;
        this.cvtermpaths = cvtermpaths;
        this.cvterms = cvterms;
    }

   
    // Property accessors

    public Integer getCvId() {
        return this.cvId;
    }
    
    public void setCvId(Integer cvId) {
        this.cvId = cvId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public Set getCvtermpaths() {
        return this.cvtermpaths;
    }
    
    public void setCvtermpaths(Set cvtermpaths) {
        this.cvtermpaths = cvtermpaths;
    }

    public Set getCvterms() {
        return this.cvterms;
    }
    
    public void setCvterms(Set cvterms) {
        this.cvterms = cvterms;
    }
   








}