package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Cvterm generated by MyEclipse - Hibernate Tools
 */

public class Cvterm  implements java.io.Serializable {


    // Fields    

     private Integer cvtermId;
     private Dbxref dbxref;
     private Cv cv;
     private String name;
     private String definition;
     private Integer isObsolete;
     private Integer isRelationshiptype;
     private Set politlocationsForCountryId = new HashSet(0);
     private Set phenotypesForObservableId = new HashSet(0);
     private Set phenotypesForAttrId = new HashSet(0);
     private Set dbxrefprops = new HashSet(0);
     private Set cvtermpropsForCvtermId = new HashSet(0);
     private Set politlocationsForCountyId = new HashSet(0);
     private Set cvtermRelationshipsForObjectId = new HashSet(0);
     private Set cvtermRelationshipsForSubjectId = new HashSet(0);
     private Set organismprops = new HashSet(0);
     private Set cvtermpathsForSubjectId = new HashSet(0);
     private Set cvtermsynonymsForTypeId = new HashSet(0);
     private Set pubs = new HashSet(0);
     private Set features = new HashSet(0);
     private Set featureGenotypes = new HashSet(0);
     private Set phendescs = new HashSet(0);
     private Set featurePubprops = new HashSet(0);
     private Set crossexperimentprops = new HashSet(0);
     private Set cvtermpropsForTypeId = new HashSet(0);
     private Set contacts = new HashSet(0);
     private Set crossexperiments = new HashSet(0);
     private Set gtassaies = new HashSet(0);
     private Set phenotypesForCvalueId = new HashSet(0);
     private Set specimensForTissueTypeId = new HashSet(0);
     private Set phenotypeCvterms = new HashSet(0);
     private Set individualBiotypes = new HashSet(0);
     private Set environmentCvterms = new HashSet(0);
     private Set featureRelationshipprops = new HashSet(0);
     private Set ptassayprops = new HashSet(0);
     private Set featureRelationships = new HashSet(0);
     private Set synonyms = new HashSet(0);
     private Set cvtermDbxrefs = new HashSet(0);
     private Set cvtermpathsForTypeId = new HashSet(0);
     private Set cvtermRelationshipsForTypeId = new HashSet(0);
     private Set reagentRelationships = new HashSet(0);
     private Set specimensForExtractTypeId = new HashSet(0);
     private Set pubprops = new HashSet(0);
     private Set featureprops = new HashSet(0);
     private Set cvtermpathsForObjectId = new HashSet(0);
     private Set contactRelationships = new HashSet(0);
     private Set pubRelationships = new HashSet(0);
     private Set politlocationsForProvinceId = new HashSet(0);
     private Set phenotypeComparisons = new HashSet(0);
     private Set reagentprops = new HashSet(0);
     private Set featureCvtermprops = new HashSet(0);
     private Set phenstatements = new HashSet(0);
     private Set featureCvterms = new HashSet(0);
     private Set individualprops = new HashSet(0);
     private Set cvtermsynonymsForCvtermId = new HashSet(0);
     private Set individuals = new HashSet(0);
     private Set gtassayprops = new HashSet(0);
     private Set phenotypesForAssayId = new HashSet(0);
     private Set reagents = new HashSet(0);


    // Constructors

    /** default constructor */
    public Cvterm() {
    }

	/** minimal constructor */
    public Cvterm(Dbxref dbxref, Cv cv, String name, Integer isObsolete, Integer isRelationshiptype) {
        this.dbxref = dbxref;
        this.cv = cv;
        this.name = name;
        this.isObsolete = isObsolete;
        this.isRelationshiptype = isRelationshiptype;
    }
    
    /** full constructor */
    public Cvterm(Dbxref dbxref, Cv cv, String name, String definition, Integer isObsolete, Integer isRelationshiptype, Set politlocationsForCountryId, Set phenotypesForObservableId, Set phenotypesForAttrId, Set dbxrefprops, Set cvtermpropsForCvtermId, Set politlocationsForCountyId, Set cvtermRelationshipsForObjectId, Set cvtermRelationshipsForSubjectId, Set organismprops, Set cvtermpathsForSubjectId, Set cvtermsynonymsForTypeId, Set pubs, Set features, Set featureGenotypes, Set phendescs, Set featurePubprops, Set crossexperimentprops, Set cvtermpropsForTypeId, Set contacts, Set crossexperiments, Set gtassaies, Set phenotypesForCvalueId, Set specimensForTissueTypeId, Set phenotypeCvterms, Set individualBiotypes, Set environmentCvterms, Set featureRelationshipprops, Set ptassayprops, Set featureRelationships, Set synonyms, Set cvtermDbxrefs, Set cvtermpathsForTypeId, Set cvtermRelationshipsForTypeId, Set reagentRelationships, Set specimensForExtractTypeId, Set pubprops, Set featureprops, Set cvtermpathsForObjectId, Set contactRelationships, Set pubRelationships, Set politlocationsForProvinceId, Set phenotypeComparisons, Set reagentprops, Set featureCvtermprops, Set phenstatements, Set featureCvterms, Set individualprops, Set cvtermsynonymsForCvtermId, Set individuals, Set gtassayprops, Set phenotypesForAssayId, Set reagents) {
        this.dbxref = dbxref;
        this.cv = cv;
        this.name = name;
        this.definition = definition;
        this.isObsolete = isObsolete;
        this.isRelationshiptype = isRelationshiptype;
        this.politlocationsForCountryId = politlocationsForCountryId;
        this.phenotypesForObservableId = phenotypesForObservableId;
        this.phenotypesForAttrId = phenotypesForAttrId;
        this.dbxrefprops = dbxrefprops;
        this.cvtermpropsForCvtermId = cvtermpropsForCvtermId;
        this.politlocationsForCountyId = politlocationsForCountyId;
        this.cvtermRelationshipsForObjectId = cvtermRelationshipsForObjectId;
        this.cvtermRelationshipsForSubjectId = cvtermRelationshipsForSubjectId;
        this.organismprops = organismprops;
        this.cvtermpathsForSubjectId = cvtermpathsForSubjectId;
        this.cvtermsynonymsForTypeId = cvtermsynonymsForTypeId;
        this.pubs = pubs;
        this.features = features;
        this.featureGenotypes = featureGenotypes;
        this.phendescs = phendescs;
        this.featurePubprops = featurePubprops;
        this.crossexperimentprops = crossexperimentprops;
        this.cvtermpropsForTypeId = cvtermpropsForTypeId;
        this.contacts = contacts;
        this.crossexperiments = crossexperiments;
        this.gtassaies = gtassaies;
        this.phenotypesForCvalueId = phenotypesForCvalueId;
        this.specimensForTissueTypeId = specimensForTissueTypeId;
        this.phenotypeCvterms = phenotypeCvterms;
        this.individualBiotypes = individualBiotypes;
        this.environmentCvterms = environmentCvterms;
        this.featureRelationshipprops = featureRelationshipprops;
        this.ptassayprops = ptassayprops;
        this.featureRelationships = featureRelationships;
        this.synonyms = synonyms;
        this.cvtermDbxrefs = cvtermDbxrefs;
        this.cvtermpathsForTypeId = cvtermpathsForTypeId;
        this.cvtermRelationshipsForTypeId = cvtermRelationshipsForTypeId;
        this.reagentRelationships = reagentRelationships;
        this.specimensForExtractTypeId = specimensForExtractTypeId;
        this.pubprops = pubprops;
        this.featureprops = featureprops;
        this.cvtermpathsForObjectId = cvtermpathsForObjectId;
        this.contactRelationships = contactRelationships;
        this.pubRelationships = pubRelationships;
        this.politlocationsForProvinceId = politlocationsForProvinceId;
        this.phenotypeComparisons = phenotypeComparisons;
        this.reagentprops = reagentprops;
        this.featureCvtermprops = featureCvtermprops;
        this.phenstatements = phenstatements;
        this.featureCvterms = featureCvterms;
        this.individualprops = individualprops;
        this.cvtermsynonymsForCvtermId = cvtermsynonymsForCvtermId;
        this.individuals = individuals;
        this.gtassayprops = gtassayprops;
        this.phenotypesForAssayId = phenotypesForAssayId;
        this.reagents = reagents;
    }

   
    // Property accessors

    public Integer getCvtermId() {
        return this.cvtermId;
    }
    
    public void setCvtermId(Integer cvtermId) {
        this.cvtermId = cvtermId;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }

    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public Integer getIsObsolete() {
        return this.isObsolete;
    }
    
    public void setIsObsolete(Integer isObsolete) {
        this.isObsolete = isObsolete;
    }

    public Integer getIsRelationshiptype() {
        return this.isRelationshiptype;
    }
    
    public void setIsRelationshiptype(Integer isRelationshiptype) {
        this.isRelationshiptype = isRelationshiptype;
    }

    public Set getPolitlocationsForCountryId() {
        return this.politlocationsForCountryId;
    }
    
    public void setPolitlocationsForCountryId(Set politlocationsForCountryId) {
        this.politlocationsForCountryId = politlocationsForCountryId;
    }

    public Set getPhenotypesForObservableId() {
        return this.phenotypesForObservableId;
    }
    
    public void setPhenotypesForObservableId(Set phenotypesForObservableId) {
        this.phenotypesForObservableId = phenotypesForObservableId;
    }

    public Set getPhenotypesForAttrId() {
        return this.phenotypesForAttrId;
    }
    
    public void setPhenotypesForAttrId(Set phenotypesForAttrId) {
        this.phenotypesForAttrId = phenotypesForAttrId;
    }

    public Set getDbxrefprops() {
        return this.dbxrefprops;
    }
    
    public void setDbxrefprops(Set dbxrefprops) {
        this.dbxrefprops = dbxrefprops;
    }

    public Set getCvtermpropsForCvtermId() {
        return this.cvtermpropsForCvtermId;
    }
    
    public void setCvtermpropsForCvtermId(Set cvtermpropsForCvtermId) {
        this.cvtermpropsForCvtermId = cvtermpropsForCvtermId;
    }

    public Set getPolitlocationsForCountyId() {
        return this.politlocationsForCountyId;
    }
    
    public void setPolitlocationsForCountyId(Set politlocationsForCountyId) {
        this.politlocationsForCountyId = politlocationsForCountyId;
    }

    public Set getCvtermRelationshipsForObjectId() {
        return this.cvtermRelationshipsForObjectId;
    }
    
    public void setCvtermRelationshipsForObjectId(Set cvtermRelationshipsForObjectId) {
        this.cvtermRelationshipsForObjectId = cvtermRelationshipsForObjectId;
    }

    public Set getCvtermRelationshipsForSubjectId() {
        return this.cvtermRelationshipsForSubjectId;
    }
    
    public void setCvtermRelationshipsForSubjectId(Set cvtermRelationshipsForSubjectId) {
        this.cvtermRelationshipsForSubjectId = cvtermRelationshipsForSubjectId;
    }

    public Set getOrganismprops() {
        return this.organismprops;
    }
    
    public void setOrganismprops(Set organismprops) {
        this.organismprops = organismprops;
    }

    public Set getCvtermpathsForSubjectId() {
        return this.cvtermpathsForSubjectId;
    }
    
    public void setCvtermpathsForSubjectId(Set cvtermpathsForSubjectId) {
        this.cvtermpathsForSubjectId = cvtermpathsForSubjectId;
    }

    public Set getCvtermsynonymsForTypeId() {
        return this.cvtermsynonymsForTypeId;
    }
    
    public void setCvtermsynonymsForTypeId(Set cvtermsynonymsForTypeId) {
        this.cvtermsynonymsForTypeId = cvtermsynonymsForTypeId;
    }

    public Set getPubs() {
        return this.pubs;
    }
    
    public void setPubs(Set pubs) {
        this.pubs = pubs;
    }

    public Set getFeatures() {
        return this.features;
    }
    
    public void setFeatures(Set features) {
        this.features = features;
    }

    public Set getFeatureGenotypes() {
        return this.featureGenotypes;
    }
    
    public void setFeatureGenotypes(Set featureGenotypes) {
        this.featureGenotypes = featureGenotypes;
    }

    public Set getPhendescs() {
        return this.phendescs;
    }
    
    public void setPhendescs(Set phendescs) {
        this.phendescs = phendescs;
    }

    public Set getFeaturePubprops() {
        return this.featurePubprops;
    }
    
    public void setFeaturePubprops(Set featurePubprops) {
        this.featurePubprops = featurePubprops;
    }

    public Set getCrossexperimentprops() {
        return this.crossexperimentprops;
    }
    
    public void setCrossexperimentprops(Set crossexperimentprops) {
        this.crossexperimentprops = crossexperimentprops;
    }

    public Set getCvtermpropsForTypeId() {
        return this.cvtermpropsForTypeId;
    }
    
    public void setCvtermpropsForTypeId(Set cvtermpropsForTypeId) {
        this.cvtermpropsForTypeId = cvtermpropsForTypeId;
    }

    public Set getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }

    public Set getCrossexperiments() {
        return this.crossexperiments;
    }
    
    public void setCrossexperiments(Set crossexperiments) {
        this.crossexperiments = crossexperiments;
    }

    public Set getGtassaies() {
        return this.gtassaies;
    }
    
    public void setGtassaies(Set gtassaies) {
        this.gtassaies = gtassaies;
    }

    public Set getPhenotypesForCvalueId() {
        return this.phenotypesForCvalueId;
    }
    
    public void setPhenotypesForCvalueId(Set phenotypesForCvalueId) {
        this.phenotypesForCvalueId = phenotypesForCvalueId;
    }

    public Set getSpecimensForTissueTypeId() {
        return this.specimensForTissueTypeId;
    }
    
    public void setSpecimensForTissueTypeId(Set specimensForTissueTypeId) {
        this.specimensForTissueTypeId = specimensForTissueTypeId;
    }

    public Set getPhenotypeCvterms() {
        return this.phenotypeCvterms;
    }
    
    public void setPhenotypeCvterms(Set phenotypeCvterms) {
        this.phenotypeCvterms = phenotypeCvterms;
    }

    public Set getIndividualBiotypes() {
        return this.individualBiotypes;
    }
    
    public void setIndividualBiotypes(Set individualBiotypes) {
        this.individualBiotypes = individualBiotypes;
    }

    public Set getEnvironmentCvterms() {
        return this.environmentCvterms;
    }
    
    public void setEnvironmentCvterms(Set environmentCvterms) {
        this.environmentCvterms = environmentCvterms;
    }

    public Set getFeatureRelationshipprops() {
        return this.featureRelationshipprops;
    }
    
    public void setFeatureRelationshipprops(Set featureRelationshipprops) {
        this.featureRelationshipprops = featureRelationshipprops;
    }

    public Set getPtassayprops() {
        return this.ptassayprops;
    }
    
    public void setPtassayprops(Set ptassayprops) {
        this.ptassayprops = ptassayprops;
    }

    public Set getFeatureRelationships() {
        return this.featureRelationships;
    }
    
    public void setFeatureRelationships(Set featureRelationships) {
        this.featureRelationships = featureRelationships;
    }

    public Set getSynonyms() {
        return this.synonyms;
    }
    
    public void setSynonyms(Set synonyms) {
        this.synonyms = synonyms;
    }

    public Set getCvtermDbxrefs() {
        return this.cvtermDbxrefs;
    }
    
    public void setCvtermDbxrefs(Set cvtermDbxrefs) {
        this.cvtermDbxrefs = cvtermDbxrefs;
    }

    public Set getCvtermpathsForTypeId() {
        return this.cvtermpathsForTypeId;
    }
    
    public void setCvtermpathsForTypeId(Set cvtermpathsForTypeId) {
        this.cvtermpathsForTypeId = cvtermpathsForTypeId;
    }

    public Set getCvtermRelationshipsForTypeId() {
        return this.cvtermRelationshipsForTypeId;
    }
    
    public void setCvtermRelationshipsForTypeId(Set cvtermRelationshipsForTypeId) {
        this.cvtermRelationshipsForTypeId = cvtermRelationshipsForTypeId;
    }

    public Set getReagentRelationships() {
        return this.reagentRelationships;
    }
    
    public void setReagentRelationships(Set reagentRelationships) {
        this.reagentRelationships = reagentRelationships;
    }

    public Set getSpecimensForExtractTypeId() {
        return this.specimensForExtractTypeId;
    }
    
    public void setSpecimensForExtractTypeId(Set specimensForExtractTypeId) {
        this.specimensForExtractTypeId = specimensForExtractTypeId;
    }

    public Set getPubprops() {
        return this.pubprops;
    }
    
    public void setPubprops(Set pubprops) {
        this.pubprops = pubprops;
    }

    public Set getFeatureprops() {
        return this.featureprops;
    }
    
    public void setFeatureprops(Set featureprops) {
        this.featureprops = featureprops;
    }

    public Set getCvtermpathsForObjectId() {
        return this.cvtermpathsForObjectId;
    }
    
    public void setCvtermpathsForObjectId(Set cvtermpathsForObjectId) {
        this.cvtermpathsForObjectId = cvtermpathsForObjectId;
    }

    public Set getContactRelationships() {
        return this.contactRelationships;
    }
    
    public void setContactRelationships(Set contactRelationships) {
        this.contactRelationships = contactRelationships;
    }

    public Set getPubRelationships() {
        return this.pubRelationships;
    }
    
    public void setPubRelationships(Set pubRelationships) {
        this.pubRelationships = pubRelationships;
    }

    public Set getPolitlocationsForProvinceId() {
        return this.politlocationsForProvinceId;
    }
    
    public void setPolitlocationsForProvinceId(Set politlocationsForProvinceId) {
        this.politlocationsForProvinceId = politlocationsForProvinceId;
    }

    public Set getPhenotypeComparisons() {
        return this.phenotypeComparisons;
    }
    
    public void setPhenotypeComparisons(Set phenotypeComparisons) {
        this.phenotypeComparisons = phenotypeComparisons;
    }

    public Set getReagentprops() {
        return this.reagentprops;
    }
    
    public void setReagentprops(Set reagentprops) {
        this.reagentprops = reagentprops;
    }

    public Set getFeatureCvtermprops() {
        return this.featureCvtermprops;
    }
    
    public void setFeatureCvtermprops(Set featureCvtermprops) {
        this.featureCvtermprops = featureCvtermprops;
    }

    public Set getPhenstatements() {
        return this.phenstatements;
    }
    
    public void setPhenstatements(Set phenstatements) {
        this.phenstatements = phenstatements;
    }

    public Set getFeatureCvterms() {
        return this.featureCvterms;
    }
    
    public void setFeatureCvterms(Set featureCvterms) {
        this.featureCvterms = featureCvterms;
    }

    public Set getIndividualprops() {
        return this.individualprops;
    }
    
    public void setIndividualprops(Set individualprops) {
        this.individualprops = individualprops;
    }

    public Set getCvtermsynonymsForCvtermId() {
        return this.cvtermsynonymsForCvtermId;
    }
    
    public void setCvtermsynonymsForCvtermId(Set cvtermsynonymsForCvtermId) {
        this.cvtermsynonymsForCvtermId = cvtermsynonymsForCvtermId;
    }

    public Set getIndividuals() {
        return this.individuals;
    }
    
    public void setIndividuals(Set individuals) {
        this.individuals = individuals;
    }

    public Set getGtassayprops() {
        return this.gtassayprops;
    }
    
    public void setGtassayprops(Set gtassayprops) {
        this.gtassayprops = gtassayprops;
    }

    public Set getPhenotypesForAssayId() {
        return this.phenotypesForAssayId;
    }
    
    public void setPhenotypesForAssayId(Set phenotypesForAssayId) {
        this.phenotypesForAssayId = phenotypesForAssayId;
    }

    public Set getReagents() {
        return this.reagents;
    }
    
    public void setReagents(Set reagents) {
        this.reagents = reagents;
    }
   








}