package org.nescent.heliconius.hibernate;



/**
 * Cvtermprop generated by MyEclipse - Hibernate Tools
 */

public class Cvtermprop  implements java.io.Serializable {


    // Fields    

     private Integer cvtermpropId;
     private Cvterm cvtermByCvtermId;
     private Cvterm cvtermByTypeId;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public Cvtermprop() {
    }

    
    /** full constructor */
    public Cvtermprop(Cvterm cvtermByCvtermId, Cvterm cvtermByTypeId, String value, Integer rank) {
        this.cvtermByCvtermId = cvtermByCvtermId;
        this.cvtermByTypeId = cvtermByTypeId;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getCvtermpropId() {
        return this.cvtermpropId;
    }
    
    public void setCvtermpropId(Integer cvtermpropId) {
        this.cvtermpropId = cvtermpropId;
    }

    public Cvterm getCvtermByCvtermId() {
        return this.cvtermByCvtermId;
    }
    
    public void setCvtermByCvtermId(Cvterm cvtermByCvtermId) {
        this.cvtermByCvtermId = cvtermByCvtermId;
    }

    public Cvterm getCvtermByTypeId() {
        return this.cvtermByTypeId;
    }
    
    public void setCvtermByTypeId(Cvterm cvtermByTypeId) {
        this.cvtermByTypeId = cvtermByTypeId;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}