package org.nescent.heliconius.hibernate;



/**
 * CvtermRelationship generated by MyEclipse - Hibernate Tools
 */

public class CvtermRelationship  implements java.io.Serializable {


    // Fields    

     private Integer cvtermRelationshipId;
     private Cvterm cvtermBySubjectId;
     private Cvterm cvtermByObjectId;
     private Cvterm cvtermByTypeId;


    // Constructors

    /** default constructor */
    public CvtermRelationship() {
    }

    
    /** full constructor */
    public CvtermRelationship(Cvterm cvtermBySubjectId, Cvterm cvtermByObjectId, Cvterm cvtermByTypeId) {
        this.cvtermBySubjectId = cvtermBySubjectId;
        this.cvtermByObjectId = cvtermByObjectId;
        this.cvtermByTypeId = cvtermByTypeId;
    }

   
    // Property accessors

    public Integer getCvtermRelationshipId() {
        return this.cvtermRelationshipId;
    }
    
    public void setCvtermRelationshipId(Integer cvtermRelationshipId) {
        this.cvtermRelationshipId = cvtermRelationshipId;
    }

    public Cvterm getCvtermBySubjectId() {
        return this.cvtermBySubjectId;
    }
    
    public void setCvtermBySubjectId(Cvterm cvtermBySubjectId) {
        this.cvtermBySubjectId = cvtermBySubjectId;
    }

    public Cvterm getCvtermByObjectId() {
        return this.cvtermByObjectId;
    }
    
    public void setCvtermByObjectId(Cvterm cvtermByObjectId) {
        this.cvtermByObjectId = cvtermByObjectId;
    }

    public Cvterm getCvtermByTypeId() {
        return this.cvtermByTypeId;
    }
    
    public void setCvtermByTypeId(Cvterm cvtermByTypeId) {
        this.cvtermByTypeId = cvtermByTypeId;
    }
   








}