package org.nescent.heliconius.hibernate;



/**
 * Cvtermsynonym generated by MyEclipse - Hibernate Tools
 */

public class Cvtermsynonym  implements java.io.Serializable {


    // Fields    

     private Integer cvtermsynonymId;
     private Cvterm cvtermByCvtermId;
     private Cvterm cvtermByTypeId;
     private String synonym;


    // Constructors

    /** default constructor */
    public Cvtermsynonym() {
    }

	/** minimal constructor */
    public Cvtermsynonym(Cvterm cvtermByCvtermId, String synonym) {
        this.cvtermByCvtermId = cvtermByCvtermId;
        this.synonym = synonym;
    }
    
    /** full constructor */
    public Cvtermsynonym(Cvterm cvtermByCvtermId, Cvterm cvtermByTypeId, String synonym) {
        this.cvtermByCvtermId = cvtermByCvtermId;
        this.cvtermByTypeId = cvtermByTypeId;
        this.synonym = synonym;
    }

   
    // Property accessors

    public Integer getCvtermsynonymId() {
        return this.cvtermsynonymId;
    }
    
    public void setCvtermsynonymId(Integer cvtermsynonymId) {
        this.cvtermsynonymId = cvtermsynonymId;
    }

    public Cvterm getCvtermByCvtermId() {
        return this.cvtermByCvtermId;
    }
    
    public void setCvtermByCvtermId(Cvterm cvtermByCvtermId) {
        this.cvtermByCvtermId = cvtermByCvtermId;
    }

    public Cvterm getCvtermByTypeId() {
        return this.cvtermByTypeId;
    }
    
    public void setCvtermByTypeId(Cvterm cvtermByTypeId) {
        this.cvtermByTypeId = cvtermByTypeId;
    }

    public String getSynonym() {
        return this.synonym;
    }
    
    public void setSynonym(String synonym) {
        this.synonym = synonym;
    }
   








}