package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Dbxref generated by MyEclipse - Hibernate Tools
 */

public class Dbxref  implements java.io.Serializable {


    // Fields    

     private Integer dbxrefId;
     private Db db;
     private String accession;
     private String version;
     private String description;
     private Set dbxrefprops = new HashSet(0);
     private Set featureCvtermDbxrefs = new HashSet(0);
     private Set features = new HashSet(0);
     private Set featureDbxrefs = new HashSet(0);
     private Set cvterms = new HashSet(0);
     private Set pubDbxrefs = new HashSet(0);
     private Set organismDbxrefs = new HashSet(0);
     private Set cvtermDbxrefs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Dbxref() {
    }

	/** minimal constructor */
    public Dbxref(Db db, String accession, String version) {
        this.db = db;
        this.accession = accession;
        this.version = version;
    }
    
    /** full constructor */
    public Dbxref(Db db, String accession, String version, String description, Set dbxrefprops, Set featureCvtermDbxrefs, Set features, Set featureDbxrefs, Set cvterms, Set pubDbxrefs, Set organismDbxrefs, Set cvtermDbxrefs) {
        this.db = db;
        this.accession = accession;
        this.version = version;
        this.description = description;
        this.dbxrefprops = dbxrefprops;
        this.featureCvtermDbxrefs = featureCvtermDbxrefs;
        this.features = features;
        this.featureDbxrefs = featureDbxrefs;
        this.cvterms = cvterms;
        this.pubDbxrefs = pubDbxrefs;
        this.organismDbxrefs = organismDbxrefs;
        this.cvtermDbxrefs = cvtermDbxrefs;
    }

   
    // Property accessors

    public Integer getDbxrefId() {
        return this.dbxrefId;
    }
    
    public void setDbxrefId(Integer dbxrefId) {
        this.dbxrefId = dbxrefId;
    }

    public Db getDb() {
        return this.db;
    }
    
    public void setDb(Db db) {
        this.db = db;
    }

    public String getAccession() {
        return this.accession;
    }
    
    public void setAccession(String accession) {
        this.accession = accession;
    }

    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getDbxrefprops() {
        return this.dbxrefprops;
    }
    
    public void setDbxrefprops(Set dbxrefprops) {
        this.dbxrefprops = dbxrefprops;
    }

    public Set getFeatureCvtermDbxrefs() {
        return this.featureCvtermDbxrefs;
    }
    
    public void setFeatureCvtermDbxrefs(Set featureCvtermDbxrefs) {
        this.featureCvtermDbxrefs = featureCvtermDbxrefs;
    }

    public Set getFeatures() {
        return this.features;
    }
    
    public void setFeatures(Set features) {
        this.features = features;
    }

    public Set getFeatureDbxrefs() {
        return this.featureDbxrefs;
    }
    
    public void setFeatureDbxrefs(Set featureDbxrefs) {
        this.featureDbxrefs = featureDbxrefs;
    }

    public Set getCvterms() {
        return this.cvterms;
    }
    
    public void setCvterms(Set cvterms) {
        this.cvterms = cvterms;
    }

    public Set getPubDbxrefs() {
        return this.pubDbxrefs;
    }
    
    public void setPubDbxrefs(Set pubDbxrefs) {
        this.pubDbxrefs = pubDbxrefs;
    }

    public Set getOrganismDbxrefs() {
        return this.organismDbxrefs;
    }
    
    public void setOrganismDbxrefs(Set organismDbxrefs) {
        this.organismDbxrefs = organismDbxrefs;
    }

    public Set getCvtermDbxrefs() {
        return this.cvtermDbxrefs;
    }
    
    public void setCvtermDbxrefs(Set cvtermDbxrefs) {
        this.cvtermDbxrefs = cvtermDbxrefs;
    }
   








}