package org.nescent.heliconius.hibernate;



/**
 * EnvironmentCvterm generated by MyEclipse - Hibernate Tools
 */

public class EnvironmentCvterm  implements java.io.Serializable {


    // Fields    

     private Integer environmentCvtermId;
     private Cvterm cvterm;
     private Environment environment;


    // Constructors

    /** default constructor */
    public EnvironmentCvterm() {
    }

    
    /** full constructor */
    public EnvironmentCvterm(Cvterm cvterm, Environment environment) {
        this.cvterm = cvterm;
        this.environment = environment;
    }

   
    // Property accessors

    public Integer getEnvironmentCvtermId() {
        return this.environmentCvtermId;
    }
    
    public void setEnvironmentCvtermId(Integer environmentCvtermId) {
        this.environmentCvtermId = environmentCvtermId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Environment getEnvironment() {
        return this.environment;
    }
    
    public void setEnvironment(Environment environment) {
        this.environment = environment;
    }
   








}