package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Environment generated by MyEclipse - Hibernate Tools
 */

public class Environment  implements java.io.Serializable {


    // Fields    

     private Integer environmentId;
     private String uniquename;
     private String description;
     private Set phendescs = new HashSet(0);
     private Set phenotypeComparisonsForEnvironment2Id = new HashSet(0);
     private Set environmentCvterms = new HashSet(0);
     private Set phenotypeComparisonsForEnvironment1Id = new HashSet(0);
     private Set phenstatements = new HashSet(0);


    // Constructors

    /** default constructor */
    public Environment() {
    }

	/** minimal constructor */
    public Environment(String uniquename) {
        this.uniquename = uniquename;
    }
    
    /** full constructor */
    public Environment(String uniquename, String description, Set phendescs, Set phenotypeComparisonsForEnvironment2Id, Set environmentCvterms, Set phenotypeComparisonsForEnvironment1Id, Set phenstatements) {
        this.uniquename = uniquename;
        this.description = description;
        this.phendescs = phendescs;
        this.phenotypeComparisonsForEnvironment2Id = phenotypeComparisonsForEnvironment2Id;
        this.environmentCvterms = environmentCvterms;
        this.phenotypeComparisonsForEnvironment1Id = phenotypeComparisonsForEnvironment1Id;
        this.phenstatements = phenstatements;
    }

   
    // Property accessors

    public Integer getEnvironmentId() {
        return this.environmentId;
    }
    
    public void setEnvironmentId(Integer environmentId) {
        this.environmentId = environmentId;
    }

    public String getUniquename() {
        return this.uniquename;
    }
    
    public void setUniquename(String uniquename) {
        this.uniquename = uniquename;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getPhendescs() {
        return this.phendescs;
    }
    
    public void setPhendescs(Set phendescs) {
        this.phendescs = phendescs;
    }

    public Set getPhenotypeComparisonsForEnvironment2Id() {
        return this.phenotypeComparisonsForEnvironment2Id;
    }
    
    public void setPhenotypeComparisonsForEnvironment2Id(Set phenotypeComparisonsForEnvironment2Id) {
        this.phenotypeComparisonsForEnvironment2Id = phenotypeComparisonsForEnvironment2Id;
    }

    public Set getEnvironmentCvterms() {
        return this.environmentCvterms;
    }
    
    public void setEnvironmentCvterms(Set environmentCvterms) {
        this.environmentCvterms = environmentCvterms;
    }

    public Set getPhenotypeComparisonsForEnvironment1Id() {
        return this.phenotypeComparisonsForEnvironment1Id;
    }
    
    public void setPhenotypeComparisonsForEnvironment1Id(Set phenotypeComparisonsForEnvironment1Id) {
        this.phenotypeComparisonsForEnvironment1Id = phenotypeComparisonsForEnvironment1Id;
    }

    public Set getPhenstatements() {
        return this.phenstatements;
    }
    
    public void setPhenstatements(Set phenstatements) {
        this.phenstatements = phenstatements;
    }
   








}