package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Featureprop generated by MyEclipse - Hibernate Tools
 */

public class Featureprop  implements java.io.Serializable {


    // Fields    

     private Integer featurepropId;
     private Cvterm cvterm;
     private Feature feature;
     private String value;
     private Integer rank;
     private Set featurepropPubs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Featureprop() {
    }

	/** minimal constructor */
    public Featureprop(Cvterm cvterm, Feature feature, Integer rank) {
        this.cvterm = cvterm;
        this.feature = feature;
        this.rank = rank;
    }
    
    /** full constructor */
    public Featureprop(Cvterm cvterm, Feature feature, String value, Integer rank, Set featurepropPubs) {
        this.cvterm = cvterm;
        this.feature = feature;
        this.value = value;
        this.rank = rank;
        this.featurepropPubs = featurepropPubs;
    }

   
    // Property accessors

    public Integer getFeaturepropId() {
        return this.featurepropId;
    }
    
    public void setFeaturepropId(Integer featurepropId) {
        this.featurepropId = featurepropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Set getFeaturepropPubs() {
        return this.featurepropPubs;
    }
    
    public void setFeaturepropPubs(Set featurepropPubs) {
        this.featurepropPubs = featurepropPubs;
    }
   








}