package org.nescent.heliconius.hibernate;



/**
 * FeatureCvtermprop generated by MyEclipse - Hibernate Tools
 */

public class FeatureCvtermprop  implements java.io.Serializable {


    // Fields    

     private Integer featureCvtermpropId;
     private Cvterm cvterm;
     private FeatureCvterm featureCvterm;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public FeatureCvtermprop() {
    }

	/** minimal constructor */
    public FeatureCvtermprop(Cvterm cvterm, FeatureCvterm featureCvterm, Integer rank) {
        this.cvterm = cvterm;
        this.featureCvterm = featureCvterm;
        this.rank = rank;
    }
    
    /** full constructor */
    public FeatureCvtermprop(Cvterm cvterm, FeatureCvterm featureCvterm, String value, Integer rank) {
        this.cvterm = cvterm;
        this.featureCvterm = featureCvterm;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getFeatureCvtermpropId() {
        return this.featureCvtermpropId;
    }
    
    public void setFeatureCvtermpropId(Integer featureCvtermpropId) {
        this.featureCvtermpropId = featureCvtermpropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public FeatureCvterm getFeatureCvterm() {
        return this.featureCvterm;
    }
    
    public void setFeatureCvterm(FeatureCvterm featureCvterm) {
        this.featureCvterm = featureCvterm;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}