package org.nescent.heliconius.hibernate;



/**
 * FeatureSynonym generated by MyEclipse - Hibernate Tools
 */

public class FeatureSynonym  implements java.io.Serializable {


    // Fields    

     private Integer featureSynonymId;
     private Synonym synonym;
     private Feature feature;
     private Pub pub;
     private Byte isCurrent;
     private Byte isInternal;


    // Constructors

    /** default constructor */
    public FeatureSynonym() {
    }

    
    /** full constructor */
    public FeatureSynonym(Synonym synonym, Feature feature, Pub pub, Byte isCurrent, Byte isInternal) {
        this.synonym = synonym;
        this.feature = feature;
        this.pub = pub;
        this.isCurrent = isCurrent;
        this.isInternal = isInternal;
    }

   
    // Property accessors

    public Integer getFeatureSynonymId() {
        return this.featureSynonymId;
    }
    
    public void setFeatureSynonymId(Integer featureSynonymId) {
        this.featureSynonymId = featureSynonymId;
    }

    public Synonym getSynonym() {
        return this.synonym;
    }
    
    public void setSynonym(Synonym synonym) {
        this.synonym = synonym;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Byte getIsCurrent() {
        return this.isCurrent;
    }
    
    public void setIsCurrent(Byte isCurrent) {
        this.isCurrent = isCurrent;
    }

    public Byte getIsInternal() {
        return this.isInternal;
    }
    
    public void setIsInternal(Byte isInternal) {
        this.isInternal = isInternal;
    }
   








}