package org.nescent.heliconius.hibernate;



/**
 * FeatureDbxref generated by MyEclipse - Hibernate Tools
 */

public class FeatureDbxref  implements java.io.Serializable {


    // Fields    

     private Integer featureDbxrefId;
     private Dbxref dbxref;
     private Feature feature;
     private Byte isCurrent;


    // Constructors

    /** default constructor */
    public FeatureDbxref() {
    }

    
    /** full constructor */
    public FeatureDbxref(Dbxref dbxref, Feature feature, Byte isCurrent) {
        this.dbxref = dbxref;
        this.feature = feature;
        this.isCurrent = isCurrent;
    }

   
    // Property accessors

    public Integer getFeatureDbxrefId() {
        return this.featureDbxrefId;
    }
    
    public void setFeatureDbxrefId(Integer featureDbxrefId) {
        this.featureDbxrefId = featureDbxrefId;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public Byte getIsCurrent() {
        return this.isCurrent;
    }
    
    public void setIsCurrent(Byte isCurrent) {
        this.isCurrent = isCurrent;
    }
   








}