package org.nescent.heliconius.hibernate;



/**
 * FeaturePhenotype generated by MyEclipse - Hibernate Tools
 */

public class FeaturePhenotype  implements java.io.Serializable {


    // Fields    

     private Integer featurePhenotypeId;
     private Feature feature;
     private Phenotype phenotype;


    // Constructors

    /** default constructor */
    public FeaturePhenotype() {
    }

    
    /** full constructor */
    public FeaturePhenotype(Feature feature, Phenotype phenotype) {
        this.feature = feature;
        this.phenotype = phenotype;
    }

   
    // Property accessors

    public Integer getFeaturePhenotypeId() {
        return this.featurePhenotypeId;
    }
    
    public void setFeaturePhenotypeId(Integer featurePhenotypeId) {
        this.featurePhenotypeId = featurePhenotypeId;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public Phenotype getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(Phenotype phenotype) {
        this.phenotype = phenotype;
    }
   








}