package org.nescent.heliconius.hibernate;



/**
 * FeaturepropPub generated by MyEclipse - Hibernate Tools
 */

public class FeaturepropPub  implements java.io.Serializable {


    // Fields    

     private Integer featurepropPubId;
     private Featureprop featureprop;
     private Pub pub;


    // Constructors

    /** default constructor */
    public FeaturepropPub() {
    }

    
    /** full constructor */
    public FeaturepropPub(Featureprop featureprop, Pub pub) {
        this.featureprop = featureprop;
        this.pub = pub;
    }

   
    // Property accessors

    public Integer getFeaturepropPubId() {
        return this.featurepropPubId;
    }
    
    public void setFeaturepropPubId(Integer featurepropPubId) {
        this.featurepropPubId = featurepropPubId;
    }

    public Featureprop getFeatureprop() {
        return this.featureprop;
    }
    
    public void setFeatureprop(Featureprop featureprop) {
        this.featureprop = featureprop;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }
   








}