package org.nescent.heliconius.hibernate;



/**
 * FeatureRelationshipPub generated by MyEclipse - Hibernate Tools
 */

public class FeatureRelationshipPub  implements java.io.Serializable {


    // Fields    

     private Integer featureRelationshipPubId;
     private Pub pub;
     private FeatureRelationship featureRelationship;


    // Constructors

    /** default constructor */
    public FeatureRelationshipPub() {
    }

    
    /** full constructor */
    public FeatureRelationshipPub(Pub pub, FeatureRelationship featureRelationship) {
        this.pub = pub;
        this.featureRelationship = featureRelationship;
    }

   
    // Property accessors

    public Integer getFeatureRelationshipPubId() {
        return this.featureRelationshipPubId;
    }
    
    public void setFeatureRelationshipPubId(Integer featureRelationshipPubId) {
        this.featureRelationshipPubId = featureRelationshipPubId;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public FeatureRelationship getFeatureRelationship() {
        return this.featureRelationship;
    }
    
    public void setFeatureRelationship(FeatureRelationship featureRelationship) {
        this.featureRelationship = featureRelationship;
    }
   








}