package org.nescent.heliconius.hibernate;



/**
 * FeaturePubprop generated by MyEclipse - Hibernate Tools
 */

public class FeaturePubprop  implements java.io.Serializable {


    // Fields    

     private Integer featurePubpropId;
     private Cvterm cvterm;
     private FeaturePub featurePub;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public FeaturePubprop() {
    }

	/** minimal constructor */
    public FeaturePubprop(Cvterm cvterm, FeaturePub featurePub, Integer rank) {
        this.cvterm = cvterm;
        this.featurePub = featurePub;
        this.rank = rank;
    }
    
    /** full constructor */
    public FeaturePubprop(Cvterm cvterm, FeaturePub featurePub, String value, Integer rank) {
        this.cvterm = cvterm;
        this.featurePub = featurePub;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getFeaturePubpropId() {
        return this.featurePubpropId;
    }
    
    public void setFeaturePubpropId(Integer featurePubpropId) {
        this.featurePubpropId = featurePubpropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public FeaturePub getFeaturePub() {
        return this.featurePub;
    }
    
    public void setFeaturePub(FeaturePub featurePub) {
        this.featurePub = featurePub;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}