package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * FeatureCvterm generated by MyEclipse - Hibernate Tools
 */

public class FeatureCvterm  implements java.io.Serializable {


    // Fields    

     private Integer featureCvtermId;
     private Cvterm cvterm;
     private Feature feature;
     private Pub pub;
     private Byte isNot;
     private Set featureCvtermprops = new HashSet(0);
     private Set featureCvtermPubs = new HashSet(0);
     private Set featureCvtermDbxrefs = new HashSet(0);


    // Constructors

    /** default constructor */
    public FeatureCvterm() {
    }

	/** minimal constructor */
    public FeatureCvterm(Cvterm cvterm, Feature feature, Pub pub, Byte isNot) {
        this.cvterm = cvterm;
        this.feature = feature;
        this.pub = pub;
        this.isNot = isNot;
    }
    
    /** full constructor */
    public FeatureCvterm(Cvterm cvterm, Feature feature, Pub pub, Byte isNot, Set featureCvtermprops, Set featureCvtermPubs, Set featureCvtermDbxrefs) {
        this.cvterm = cvterm;
        this.feature = feature;
        this.pub = pub;
        this.isNot = isNot;
        this.featureCvtermprops = featureCvtermprops;
        this.featureCvtermPubs = featureCvtermPubs;
        this.featureCvtermDbxrefs = featureCvtermDbxrefs;
    }

   
    // Property accessors

    public Integer getFeatureCvtermId() {
        return this.featureCvtermId;
    }
    
    public void setFeatureCvtermId(Integer featureCvtermId) {
        this.featureCvtermId = featureCvtermId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Byte getIsNot() {
        return this.isNot;
    }
    
    public void setIsNot(Byte isNot) {
        this.isNot = isNot;
    }

    public Set getFeatureCvtermprops() {
        return this.featureCvtermprops;
    }
    
    public void setFeatureCvtermprops(Set featureCvtermprops) {
        this.featureCvtermprops = featureCvtermprops;
    }

    public Set getFeatureCvtermPubs() {
        return this.featureCvtermPubs;
    }
    
    public void setFeatureCvtermPubs(Set featureCvtermPubs) {
        this.featureCvtermPubs = featureCvtermPubs;
    }

    public Set getFeatureCvtermDbxrefs() {
        return this.featureCvtermDbxrefs;
    }
    
    public void setFeatureCvtermDbxrefs(Set featureCvtermDbxrefs) {
        this.featureCvtermDbxrefs = featureCvtermDbxrefs;
    }
   








}