package org.nescent.heliconius.hibernate;



/**
 * FeatureGenotype generated by MyEclipse - Hibernate Tools
 */

public class FeatureGenotype  implements java.io.Serializable {


    // Fields    

     private Integer featureGenotypeId;
     private Cvterm cvterm;
     private Feature featureByFeatureId;
     private Feature featureByChromosomeId;
     private Genotype genotype;
     private Integer rank;
     private Integer cgroup;


    // Constructors

    /** default constructor */
    public FeatureGenotype() {
    }

	/** minimal constructor */
    public FeatureGenotype(Cvterm cvterm, Feature featureByFeatureId, Genotype genotype, Integer rank, Integer cgroup) {
        this.cvterm = cvterm;
        this.featureByFeatureId = featureByFeatureId;
        this.genotype = genotype;
        this.rank = rank;
        this.cgroup = cgroup;
    }
    
    /** full constructor */
    public FeatureGenotype(Cvterm cvterm, Feature featureByFeatureId, Feature featureByChromosomeId, Genotype genotype, Integer rank, Integer cgroup) {
        this.cvterm = cvterm;
        this.featureByFeatureId = featureByFeatureId;
        this.featureByChromosomeId = featureByChromosomeId;
        this.genotype = genotype;
        this.rank = rank;
        this.cgroup = cgroup;
    }

   
    // Property accessors

    public Integer getFeatureGenotypeId() {
        return this.featureGenotypeId;
    }
    
    public void setFeatureGenotypeId(Integer featureGenotypeId) {
        this.featureGenotypeId = featureGenotypeId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Feature getFeatureByFeatureId() {
        return this.featureByFeatureId;
    }
    
    public void setFeatureByFeatureId(Feature featureByFeatureId) {
        this.featureByFeatureId = featureByFeatureId;
    }

    public Feature getFeatureByChromosomeId() {
        return this.featureByChromosomeId;
    }
    
    public void setFeatureByChromosomeId(Feature featureByChromosomeId) {
        this.featureByChromosomeId = featureByChromosomeId;
    }

    public Genotype getGenotype() {
        return this.genotype;
    }
    
    public void setGenotype(Genotype genotype) {
        this.genotype = genotype;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Integer getCgroup() {
        return this.cgroup;
    }
    
    public void setCgroup(Integer cgroup) {
        this.cgroup = cgroup;
    }
   








}