package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * FeatureRelationshipprop generated by MyEclipse - Hibernate Tools
 */

public class FeatureRelationshipprop  implements java.io.Serializable {


    // Fields    

     private Integer featureRelationshippropId;
     private Cvterm cvterm;
     private FeatureRelationship featureRelationship;
     private String value;
     private Integer rank;
     private Set featureRelationshippropPubs = new HashSet(0);


    // Constructors

    /** default constructor */
    public FeatureRelationshipprop() {
    }

	/** minimal constructor */
    public FeatureRelationshipprop(Cvterm cvterm, FeatureRelationship featureRelationship, Integer rank) {
        this.cvterm = cvterm;
        this.featureRelationship = featureRelationship;
        this.rank = rank;
    }
    
    /** full constructor */
    public FeatureRelationshipprop(Cvterm cvterm, FeatureRelationship featureRelationship, String value, Integer rank, Set featureRelationshippropPubs) {
        this.cvterm = cvterm;
        this.featureRelationship = featureRelationship;
        this.value = value;
        this.rank = rank;
        this.featureRelationshippropPubs = featureRelationshippropPubs;
    }

   
    // Property accessors

    public Integer getFeatureRelationshippropId() {
        return this.featureRelationshippropId;
    }
    
    public void setFeatureRelationshippropId(Integer featureRelationshippropId) {
        this.featureRelationshippropId = featureRelationshippropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public FeatureRelationship getFeatureRelationship() {
        return this.featureRelationship;
    }
    
    public void setFeatureRelationship(FeatureRelationship featureRelationship) {
        this.featureRelationship = featureRelationship;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Set getFeatureRelationshippropPubs() {
        return this.featureRelationshippropPubs;
    }
    
    public void setFeatureRelationshippropPubs(Set featureRelationshippropPubs) {
        this.featureRelationshippropPubs = featureRelationshippropPubs;
    }
   








}