package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Featureloc generated by MyEclipse - Hibernate Tools
 */

public class Featureloc  implements java.io.Serializable {


    // Fields    

     private Integer featurelocId;
     private Feature featureBySrcfeatureId;
     private Feature featureByFeatureId;
     private Integer fmin;
     private Byte isFminPartial;
     private Integer fmax;
     private Byte isFmaxPartial;
     private Short strand;
     private Integer phase;
     private String residueInfo;
     private Integer locgroup;
     private Integer rank;
     private Set featurelocPubs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Featureloc() {
    }

	/** minimal constructor */
    public Featureloc(Feature featureByFeatureId, Byte isFminPartial, Byte isFmaxPartial, Integer locgroup, Integer rank) {
        this.featureByFeatureId = featureByFeatureId;
        this.isFminPartial = isFminPartial;
        this.isFmaxPartial = isFmaxPartial;
        this.locgroup = locgroup;
        this.rank = rank;
    }
    
    /** full constructor */
    public Featureloc(Feature featureBySrcfeatureId, Feature featureByFeatureId, Integer fmin, Byte isFminPartial, Integer fmax, Byte isFmaxPartial, Short strand, Integer phase, String residueInfo, Integer locgroup, Integer rank, Set featurelocPubs) {
        this.featureBySrcfeatureId = featureBySrcfeatureId;
        this.featureByFeatureId = featureByFeatureId;
        this.fmin = fmin;
        this.isFminPartial = isFminPartial;
        this.fmax = fmax;
        this.isFmaxPartial = isFmaxPartial;
        this.strand = strand;
        this.phase = phase;
        this.residueInfo = residueInfo;
        this.locgroup = locgroup;
        this.rank = rank;
        this.featurelocPubs = featurelocPubs;
    }

   
    // Property accessors

    public Integer getFeaturelocId() {
        return this.featurelocId;
    }
    
    public void setFeaturelocId(Integer featurelocId) {
        this.featurelocId = featurelocId;
    }

    public Feature getFeatureBySrcfeatureId() {
        return this.featureBySrcfeatureId;
    }
    
    public void setFeatureBySrcfeatureId(Feature featureBySrcfeatureId) {
        this.featureBySrcfeatureId = featureBySrcfeatureId;
    }

    public Feature getFeatureByFeatureId() {
        return this.featureByFeatureId;
    }
    
    public void setFeatureByFeatureId(Feature featureByFeatureId) {
        this.featureByFeatureId = featureByFeatureId;
    }

    public Integer getFmin() {
        return this.fmin;
    }
    
    public void setFmin(Integer fmin) {
        this.fmin = fmin;
    }

    public Byte getIsFminPartial() {
        return this.isFminPartial;
    }
    
    public void setIsFminPartial(Byte isFminPartial) {
        this.isFminPartial = isFminPartial;
    }

    public Integer getFmax() {
        return this.fmax;
    }
    
    public void setFmax(Integer fmax) {
        this.fmax = fmax;
    }

    public Byte getIsFmaxPartial() {
        return this.isFmaxPartial;
    }
    
    public void setIsFmaxPartial(Byte isFmaxPartial) {
        this.isFmaxPartial = isFmaxPartial;
    }

    public Short getStrand() {
        return this.strand;
    }
    
    public void setStrand(Short strand) {
        this.strand = strand;
    }

    public Integer getPhase() {
        return this.phase;
    }
    
    public void setPhase(Integer phase) {
        this.phase = phase;
    }

    public String getResidueInfo() {
        return this.residueInfo;
    }
    
    public void setResidueInfo(String residueInfo) {
        this.residueInfo = residueInfo;
    }

    public Integer getLocgroup() {
        return this.locgroup;
    }
    
    public void setLocgroup(Integer locgroup) {
        this.locgroup = locgroup;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Set getFeaturelocPubs() {
        return this.featurelocPubs;
    }
    
    public void setFeaturelocPubs(Set featurelocPubs) {
        this.featurelocPubs = featurelocPubs;
    }
   








}