package org.nescent.heliconius.hibernate;



/**
 * FeatureRelationshippropPub generated by MyEclipse - Hibernate Tools
 */

public class FeatureRelationshippropPub  implements java.io.Serializable {


    // Fields    

     private Integer featureRelationshippropPubId;
     private FeatureRelationshipprop featureRelationshipprop;
     private Pub pub;


    // Constructors

    /** default constructor */
    public FeatureRelationshippropPub() {
    }

    
    /** full constructor */
    public FeatureRelationshippropPub(FeatureRelationshipprop featureRelationshipprop, Pub pub) {
        this.featureRelationshipprop = featureRelationshipprop;
        this.pub = pub;
    }

   
    // Property accessors

    public Integer getFeatureRelationshippropPubId() {
        return this.featureRelationshippropPubId;
    }
    
    public void setFeatureRelationshippropPubId(Integer featureRelationshippropPubId) {
        this.featureRelationshippropPubId = featureRelationshippropPubId;
    }

    public FeatureRelationshipprop getFeatureRelationshipprop() {
        return this.featureRelationshipprop;
    }
    
    public void setFeatureRelationshipprop(FeatureRelationshipprop featureRelationshipprop) {
        this.featureRelationshipprop = featureRelationshipprop;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }
   








}