package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Genotype generated by MyEclipse - Hibernate Tools
 */

public class Genotype  implements java.io.Serializable {


    // Fields    

     private Integer genotypeId;
     private String name;
     private String uniquename;
     private String description;
     private Set phenotypeComparisonsForGenotype1Id = new HashSet(0);
     private Set phendescs = new HashSet(0);
     private Set featureGenotypes = new HashSet(0);
     private Set phenotypeComparisonsForGenotype2Id = new HashSet(0);
     private Set phenstatements = new HashSet(0);
     private Set gtexperiments = new HashSet(0);


    // Constructors

    /** default constructor */
    public Genotype() {
    }

	/** minimal constructor */
    public Genotype(String uniquename) {
        this.uniquename = uniquename;
    }
    
    /** full constructor */
    public Genotype(String name, String uniquename, String description, Set phenotypeComparisonsForGenotype1Id, Set phendescs, Set featureGenotypes, Set phenotypeComparisonsForGenotype2Id, Set phenstatements, Set gtexperiments) {
        this.name = name;
        this.uniquename = uniquename;
        this.description = description;
        this.phenotypeComparisonsForGenotype1Id = phenotypeComparisonsForGenotype1Id;
        this.phendescs = phendescs;
        this.featureGenotypes = featureGenotypes;
        this.phenotypeComparisonsForGenotype2Id = phenotypeComparisonsForGenotype2Id;
        this.phenstatements = phenstatements;
        this.gtexperiments = gtexperiments;
    }

   
    // Property accessors

    public Integer getGenotypeId() {
        return this.genotypeId;
    }
    
    public void setGenotypeId(Integer genotypeId) {
        this.genotypeId = genotypeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getUniquename() {
        return this.uniquename;
    }
    
    public void setUniquename(String uniquename) {
        this.uniquename = uniquename;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getPhenotypeComparisonsForGenotype1Id() {
        return this.phenotypeComparisonsForGenotype1Id;
    }
    
    public void setPhenotypeComparisonsForGenotype1Id(Set phenotypeComparisonsForGenotype1Id) {
        this.phenotypeComparisonsForGenotype1Id = phenotypeComparisonsForGenotype1Id;
    }

    public Set getPhendescs() {
        return this.phendescs;
    }
    
    public void setPhendescs(Set phendescs) {
        this.phendescs = phendescs;
    }

    public Set getFeatureGenotypes() {
        return this.featureGenotypes;
    }
    
    public void setFeatureGenotypes(Set featureGenotypes) {
        this.featureGenotypes = featureGenotypes;
    }

    public Set getPhenotypeComparisonsForGenotype2Id() {
        return this.phenotypeComparisonsForGenotype2Id;
    }
    
    public void setPhenotypeComparisonsForGenotype2Id(Set phenotypeComparisonsForGenotype2Id) {
        this.phenotypeComparisonsForGenotype2Id = phenotypeComparisonsForGenotype2Id;
    }

    public Set getPhenstatements() {
        return this.phenstatements;
    }
    
    public void setPhenstatements(Set phenstatements) {
        this.phenstatements = phenstatements;
    }

    public Set getGtexperiments() {
        return this.gtexperiments;
    }
    
    public void setGtexperiments(Set gtexperiments) {
        this.gtexperiments = gtexperiments;
    }
   








}