package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Gtassay generated by MyEclipse - Hibernate Tools
 */

public class Gtassay  implements java.io.Serializable {


    // Fields    

     private Integer gtassayId;
     private Organism organism;
     private Cvterm cvterm;
     private Image image;
     private Feature feature;
     private String name;
     private Set gtassayReagents = new HashSet(0);
     private Set gtexperiments = new HashSet(0);
     private Set gtassayprops = new HashSet(0);


    // Constructors

    /** default constructor */
    public Gtassay() {
    }

	/** minimal constructor */
    public Gtassay(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Gtassay(Organism organism, Cvterm cvterm, Image image, Feature feature, String name, Set gtassayReagents, Set gtexperiments, Set gtassayprops) {
        this.organism = organism;
        this.cvterm = cvterm;
        this.image = image;
        this.feature = feature;
        this.name = name;
        this.gtassayReagents = gtassayReagents;
        this.gtexperiments = gtexperiments;
        this.gtassayprops = gtassayprops;
    }

   
    // Property accessors

    public Integer getGtassayId() {
        return this.gtassayId;
    }
    
    public void setGtassayId(Integer gtassayId) {
        this.gtassayId = gtassayId;
    }

    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getGtassayReagents() {
        return this.gtassayReagents;
    }
    
    public void setGtassayReagents(Set gtassayReagents) {
        this.gtassayReagents = gtassayReagents;
    }

    public Set getGtexperiments() {
        return this.gtexperiments;
    }
    
    public void setGtexperiments(Set gtexperiments) {
        this.gtexperiments = gtexperiments;
    }

    public Set getGtassayprops() {
        return this.gtassayprops;
    }
    
    public void setGtassayprops(Set gtassayprops) {
        this.gtassayprops = gtassayprops;
    }
   








}