package org.nescent.heliconius.hibernate;



/**
 * Gtassayprop generated by MyEclipse - Hibernate Tools
 */

public class Gtassayprop  implements java.io.Serializable {


    // Fields    

     private Integer gtassaypropId;
     private Cvterm cvterm;
     private Gtassay gtassay;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public Gtassayprop() {
    }

	/** minimal constructor */
    public Gtassayprop(Cvterm cvterm, Gtassay gtassay, Integer rank) {
        this.cvterm = cvterm;
        this.gtassay = gtassay;
        this.rank = rank;
    }
    
    /** full constructor */
    public Gtassayprop(Cvterm cvterm, Gtassay gtassay, String value, Integer rank) {
        this.cvterm = cvterm;
        this.gtassay = gtassay;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getGtassaypropId() {
        return this.gtassaypropId;
    }
    
    public void setGtassaypropId(Integer gtassaypropId) {
        this.gtassaypropId = gtassaypropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Gtassay getGtassay() {
        return this.gtassay;
    }
    
    public void setGtassay(Gtassay gtassay) {
        this.gtassay = gtassay;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}