package org.nescent.heliconius.hibernate;



/**
 * GtassayReagent generated by MyEclipse - Hibernate Tools
 */

public class GtassayReagent  implements java.io.Serializable {


    // Fields    

     private Integer gtassayReagentId;
     private Reagent reagent;
     private Gtassay gtassay;
     private Integer typeId;


    // Constructors

    /** default constructor */
    public GtassayReagent() {
    }

    
    /** full constructor */
    public GtassayReagent(Reagent reagent, Gtassay gtassay, Integer typeId) {
        this.reagent = reagent;
        this.gtassay = gtassay;
        this.typeId = typeId;
    }

   
    // Property accessors

    public Integer getGtassayReagentId() {
        return this.gtassayReagentId;
    }
    
    public void setGtassayReagentId(Integer gtassayReagentId) {
        this.gtassayReagentId = gtassayReagentId;
    }

    public Reagent getReagent() {
        return this.reagent;
    }
    
    public void setReagent(Reagent reagent) {
        this.reagent = reagent;
    }

    public Gtassay getGtassay() {
        return this.gtassay;
    }
    
    public void setGtassay(Gtassay gtassay) {
        this.gtassay = gtassay;
    }

    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
   








}