package org.nescent.heliconius.hibernate;



/**
 * GtexperimentProject generated by MyEclipse - Hibernate Tools
 */

public class GtexperimentProject  implements java.io.Serializable {


    // Fields    

     private Integer gtexperimentProjectId;
     private Gtexperiment gtexperiment;
     private Project project;


    // Constructors

    /** default constructor */
    public GtexperimentProject() {
    }

    
    /** full constructor */
    public GtexperimentProject(Gtexperiment gtexperiment, Project project) {
        this.gtexperiment = gtexperiment;
        this.project = project;
    }

   
    // Property accessors

    public Integer getGtexperimentProjectId() {
        return this.gtexperimentProjectId;
    }
    
    public void setGtexperimentProjectId(Integer gtexperimentProjectId) {
        this.gtexperimentProjectId = gtexperimentProjectId;
    }

    public Gtexperiment getGtexperiment() {
        return this.gtexperiment;
    }
    
    public void setGtexperiment(Gtexperiment gtexperiment) {
        this.gtexperiment = gtexperiment;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
   








}