package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Gtexperiment generated by MyEclipse - Hibernate Tools
 */

public class Gtexperiment  implements java.io.Serializable {


    // Fields    

     private Integer gtexperimentId;
     private Specimen specimen;
     private Contact contact;
     private Pub pub;
     private Gtassay gtassay;
     private Genotype genotype;
     private Date experimentDate;
     private String notes;
     private Set gtexperimentProjects = new HashSet(0);


    // Constructors

    /** default constructor */
    public Gtexperiment() {
    }

	/** minimal constructor */
    public Gtexperiment(Specimen specimen, Gtassay gtassay) {
        this.specimen = specimen;
        this.gtassay = gtassay;
    }
    
    /** full constructor */
    public Gtexperiment(Specimen specimen, Contact contact, Pub pub, Gtassay gtassay, Genotype genotype, Date experimentDate, String notes, Set gtexperimentProjects) {
        this.specimen = specimen;
        this.contact = contact;
        this.pub = pub;
        this.gtassay = gtassay;
        this.genotype = genotype;
        this.experimentDate = experimentDate;
        this.notes = notes;
        this.gtexperimentProjects = gtexperimentProjects;
    }

   
    // Property accessors

    public Integer getGtexperimentId() {
        return this.gtexperimentId;
    }
    
    public void setGtexperimentId(Integer gtexperimentId) {
        this.gtexperimentId = gtexperimentId;
    }

    public Specimen getSpecimen() {
        return this.specimen;
    }
    
    public void setSpecimen(Specimen specimen) {
        this.specimen = specimen;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Gtassay getGtassay() {
        return this.gtassay;
    }
    
    public void setGtassay(Gtassay gtassay) {
        this.gtassay = gtassay;
    }

    public Genotype getGenotype() {
        return this.genotype;
    }
    
    public void setGenotype(Genotype genotype) {
        this.genotype = genotype;
    }

    public Date getExperimentDate() {
        return this.experimentDate;
    }
    
    public void setExperimentDate(Date experimentDate) {
        this.experimentDate = experimentDate;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set getGtexperimentProjects() {
        return this.gtexperimentProjects;
    }
    
    public void setGtexperimentProjects(Set gtexperimentProjects) {
        this.gtexperimentProjects = gtexperimentProjects;
    }
   








}