package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Image generated by MyEclipse - Hibernate Tools
 */

public class Image  implements java.io.Serializable {


    // Fields    

     private Integer imageId;
     private String identifier;
     private String uri;
     private Set specimenImages = new HashSet(0);
     private Set individualImages = new HashSet(0);
     private Set gtassaies = new HashSet(0);


    // Constructors

    /** default constructor */
    public Image() {
    }

	/** minimal constructor */
    public Image(String uri) {
        this.uri = uri;
    }
    
    /** full constructor */
    public Image(String identifier, String uri, Set specimenImages, Set individualImages, Set gtassaies) {
        this.identifier = identifier;
        this.uri = uri;
        this.specimenImages = specimenImages;
        this.individualImages = individualImages;
        this.gtassaies = gtassaies;
    }

   
    // Property accessors

    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    public Set getSpecimenImages() {
        return this.specimenImages;
    }
    
    public void setSpecimenImages(Set specimenImages) {
        this.specimenImages = specimenImages;
    }

    public Set getIndividualImages() {
        return this.individualImages;
    }
    
    public void setIndividualImages(Set individualImages) {
        this.individualImages = individualImages;
    }

    public Set getGtassaies() {
        return this.gtassaies;
    }
    
    public void setGtassaies(Set gtassaies) {
        this.gtassaies = gtassaies;
    }
   








}