package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * IndividualPhenotype generated by MyEclipse - Hibernate Tools
 */

public class IndividualPhenotype  implements java.io.Serializable {


    // Fields    

     private Integer individualPhenotypeId;
     private Individual individual;
     private Contact contact;
     private Ptassay ptassay;
     private Pub pub;
     private Phenotype phenotype;
     private Date assayDate;
     private String notes;
     private Set individualPhenotypeProjects = new HashSet(0);


    // Constructors

    /** default constructor */
    public IndividualPhenotype() {
    }

	/** minimal constructor */
    public IndividualPhenotype(Individual individual) {
        this.individual = individual;
    }
    
    /** full constructor */
    public IndividualPhenotype(Individual individual, Contact contact, Ptassay ptassay, Pub pub, Phenotype phenotype, Date assayDate, String notes, Set individualPhenotypeProjects) {
        this.individual = individual;
        this.contact = contact;
        this.ptassay = ptassay;
        this.pub = pub;
        this.phenotype = phenotype;
        this.assayDate = assayDate;
        this.notes = notes;
        this.individualPhenotypeProjects = individualPhenotypeProjects;
    }

   
    // Property accessors

    public Integer getIndividualPhenotypeId() {
        return this.individualPhenotypeId;
    }
    
    public void setIndividualPhenotypeId(Integer individualPhenotypeId) {
        this.individualPhenotypeId = individualPhenotypeId;
    }

    public Individual getIndividual() {
        return this.individual;
    }
    
    public void setIndividual(Individual individual) {
        this.individual = individual;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Ptassay getPtassay() {
        return this.ptassay;
    }
    
    public void setPtassay(Ptassay ptassay) {
        this.ptassay = ptassay;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Phenotype getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(Phenotype phenotype) {
        this.phenotype = phenotype;
    }

    public Date getAssayDate() {
        return this.assayDate;
    }
    
    public void setAssayDate(Date assayDate) {
        this.assayDate = assayDate;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set getIndividualPhenotypeProjects() {
        return this.individualPhenotypeProjects;
    }
    
    public void setIndividualPhenotypeProjects(Set individualPhenotypeProjects) {
        this.individualPhenotypeProjects = individualPhenotypeProjects;
    }
   








}