package org.nescent.heliconius.hibernate;



/**
 * IndividualPhenotypeProject generated by MyEclipse - Hibernate Tools
 */

public class IndividualPhenotypeProject  implements java.io.Serializable {


    // Fields    

     private Integer individualPhenotypeProjectId;
     private Project project;
     private IndividualPhenotype individualPhenotype;


    // Constructors

    /** default constructor */
    public IndividualPhenotypeProject() {
    }

    
    /** full constructor */
    public IndividualPhenotypeProject(Project project, IndividualPhenotype individualPhenotype) {
        this.project = project;
        this.individualPhenotype = individualPhenotype;
    }

   
    // Property accessors

    public Integer getIndividualPhenotypeProjectId() {
        return this.individualPhenotypeProjectId;
    }
    
    public void setIndividualPhenotypeProjectId(Integer individualPhenotypeProjectId) {
        this.individualPhenotypeProjectId = individualPhenotypeProjectId;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public IndividualPhenotype getIndividualPhenotype() {
        return this.individualPhenotype;
    }
    
    public void setIndividualPhenotype(IndividualPhenotype individualPhenotype) {
        this.individualPhenotype = individualPhenotype;
    }
   








}