package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Individual generated by MyEclipse - Hibernate Tools
 */

public class Individual  implements java.io.Serializable {


    // Fields    

     private Integer individualId;
     private Stock stock;
     private Organism organism;
     private Cvterm cvterm;
     private Crossexperiment crossexperiment;
     private Contact contact;
     private Geolocation geolocation;
     private String name;
     private String description;
     private Boolean isCaptivityReared;
     private Date collectionDate;
     private Set individualPhenotypes = new HashSet(0);
     private Set individualBiotypes = new HashSet(0);
     private Set crossexperimentsForMaleId = new HashSet(0);
     private Set specimens = new HashSet(0);
     private Set individualprops = new HashSet(0);
     private Set crossexperimentsForFemaleId = new HashSet(0);
     private Set individualImages = new HashSet(0);


    // Constructors

    /** default constructor */
    public Individual() {
    }

	/** minimal constructor */
    public Individual(String name, Boolean isCaptivityReared) {
        this.name = name;
        this.isCaptivityReared = isCaptivityReared;
    }
    
    /** full constructor */
    public Individual(Stock stock, Organism organism, Cvterm cvterm, Crossexperiment crossexperiment, Contact contact, Geolocation geolocation, String name, String description, Boolean isCaptivityReared, Date collectionDate, Set individualPhenotypes, Set individualBiotypes, Set crossexperimentsForMaleId, Set specimens, Set individualprops, Set crossexperimentsForFemaleId, Set individualImages) {
        this.stock = stock;
        this.organism = organism;
        this.cvterm = cvterm;
        this.crossexperiment = crossexperiment;
        this.contact = contact;
        this.geolocation = geolocation;
        this.name = name;
        this.description = description;
        this.isCaptivityReared = isCaptivityReared;
        this.collectionDate = collectionDate;
        this.individualPhenotypes = individualPhenotypes;
        this.individualBiotypes = individualBiotypes;
        this.crossexperimentsForMaleId = crossexperimentsForMaleId;
        this.specimens = specimens;
        this.individualprops = individualprops;
        this.crossexperimentsForFemaleId = crossexperimentsForFemaleId;
        this.individualImages = individualImages;
    }

   
    // Property accessors

    public Integer getIndividualId() {
        return this.individualId;
    }
    
    public void setIndividualId(Integer individualId) {
        this.individualId = individualId;
    }

    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }

    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Crossexperiment getCrossexperiment() {
        return this.crossexperiment;
    }
    
    public void setCrossexperiment(Crossexperiment crossexperiment) {
        this.crossexperiment = crossexperiment;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Geolocation getGeolocation() {
        return this.geolocation;
    }
    
    public void setGeolocation(Geolocation geolocation) {
        this.geolocation = geolocation;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getIsCaptivityReared() {
        return this.isCaptivityReared;
    }
    
    public void setIsCaptivityReared(Boolean isCaptivityReared) {
        this.isCaptivityReared = isCaptivityReared;
    }

    public Date getCollectionDate() {
        return this.collectionDate;
    }
    
    public void setCollectionDate(Date collectionDate) {
        this.collectionDate = collectionDate;
    }

    public Set getIndividualPhenotypes() {
        return this.individualPhenotypes;
    }
    
    public void setIndividualPhenotypes(Set individualPhenotypes) {
        this.individualPhenotypes = individualPhenotypes;
    }

    public Set getIndividualBiotypes() {
        return this.individualBiotypes;
    }
    
    public void setIndividualBiotypes(Set individualBiotypes) {
        this.individualBiotypes = individualBiotypes;
    }

    public Set getCrossexperimentsForMaleId() {
        return this.crossexperimentsForMaleId;
    }
    
    public void setCrossexperimentsForMaleId(Set crossexperimentsForMaleId) {
        this.crossexperimentsForMaleId = crossexperimentsForMaleId;
    }

    public Set getSpecimens() {
        return this.specimens;
    }
    
    public void setSpecimens(Set specimens) {
        this.specimens = specimens;
    }

    public Set getIndividualprops() {
        return this.individualprops;
    }
    
    public void setIndividualprops(Set individualprops) {
        this.individualprops = individualprops;
    }

    public Set getCrossexperimentsForFemaleId() {
        return this.crossexperimentsForFemaleId;
    }
    
    public void setCrossexperimentsForFemaleId(Set crossexperimentsForFemaleId) {
        this.crossexperimentsForFemaleId = crossexperimentsForFemaleId;
    }

    public Set getIndividualImages() {
        return this.individualImages;
    }
    
    public void setIndividualImages(Set individualImages) {
        this.individualImages = individualImages;
    }
   








}