package org.nescent.heliconius.hibernate;



/**
 * IndividualBiotype generated by MyEclipse - Hibernate Tools
 */

public class IndividualBiotype  implements java.io.Serializable {


    // Fields    

     private Integer individualBiotypeId;
     private Individual individual;
     private Cvterm cvterm;
     private Biotype biotype;


    // Constructors

    /** default constructor */
    public IndividualBiotype() {
    }

    
    /** full constructor */
    public IndividualBiotype(Individual individual, Cvterm cvterm, Biotype biotype) {
        this.individual = individual;
        this.cvterm = cvterm;
        this.biotype = biotype;
    }

   
    // Property accessors

    public Integer getIndividualBiotypeId() {
        return this.individualBiotypeId;
    }
    
    public void setIndividualBiotypeId(Integer individualBiotypeId) {
        this.individualBiotypeId = individualBiotypeId;
    }

    public Individual getIndividual() {
        return this.individual;
    }
    
    public void setIndividual(Individual individual) {
        this.individual = individual;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Biotype getBiotype() {
        return this.biotype;
    }
    
    public void setBiotype(Biotype biotype) {
        this.biotype = biotype;
    }
   








}