package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Organism generated by MyEclipse - Hibernate Tools
 */

public class Organism  implements java.io.Serializable {


    // Fields    

     private Integer organismId;
     private String abbreviation;
     private String genus;
     private String species;
     private String commonName;
     private String comment;
     private Set organismprops = new HashSet(0);
     private Set features = new HashSet(0);
     private Set individuals = new HashSet(0);
     private Set organismDbxrefs = new HashSet(0);
     private Set gtassaies = new HashSet(0);
     private Set biotypeOrganisms = new HashSet(0);


    // Constructors

    /** default constructor */
    public Organism() {
    }

	/** minimal constructor */
    public Organism(String genus, String species) {
        this.genus = genus;
        this.species = species;
    }
    
    /** full constructor */
    public Organism(String abbreviation, String genus, String species, String commonName, String comment, Set organismprops, Set features, Set individuals, Set organismDbxrefs, Set gtassaies, Set biotypeOrganisms) {
        this.abbreviation = abbreviation;
        this.genus = genus;
        this.species = species;
        this.commonName = commonName;
        this.comment = comment;
        this.organismprops = organismprops;
        this.features = features;
        this.individuals = individuals;
        this.organismDbxrefs = organismDbxrefs;
        this.gtassaies = gtassaies;
        this.biotypeOrganisms = biotypeOrganisms;
    }

   
    // Property accessors

    public Integer getOrganismId() {
        return this.organismId;
    }
    
    public void setOrganismId(Integer organismId) {
        this.organismId = organismId;
    }

    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getGenus() {
        return this.genus;
    }
    
    public void setGenus(String genus) {
        this.genus = genus;
    }

    public String getSpecies() {
        return this.species;
    }
    
    public void setSpecies(String species) {
        this.species = species;
    }

    public String getCommonName() {
        return this.commonName;
    }
    
    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }

    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    public Set getOrganismprops() {
        return this.organismprops;
    }
    
    public void setOrganismprops(Set organismprops) {
        this.organismprops = organismprops;
    }

    public Set getFeatures() {
        return this.features;
    }
    
    public void setFeatures(Set features) {
        this.features = features;
    }

    public Set getIndividuals() {
        return this.individuals;
    }
    
    public void setIndividuals(Set individuals) {
        this.individuals = individuals;
    }

    public Set getOrganismDbxrefs() {
        return this.organismDbxrefs;
    }
    
    public void setOrganismDbxrefs(Set organismDbxrefs) {
        this.organismDbxrefs = organismDbxrefs;
    }

    public Set getGtassaies() {
        return this.gtassaies;
    }
    
    public void setGtassaies(Set gtassaies) {
        this.gtassaies = gtassaies;
    }

    public Set getBiotypeOrganisms() {
        return this.biotypeOrganisms;
    }
    
    public void setBiotypeOrganisms(Set biotypeOrganisms) {
        this.biotypeOrganisms = biotypeOrganisms;
    }
   








}