package org.nescent.heliconius.hibernate;



/**
 * OrganismDbxref generated by MyEclipse - Hibernate Tools
 */

public class OrganismDbxref  implements java.io.Serializable {


    // Fields    

     private Integer organismDbxrefId;
     private Organism organism;
     private Dbxref dbxref;


    // Constructors

    /** default constructor */
    public OrganismDbxref() {
    }

    
    /** full constructor */
    public OrganismDbxref(Organism organism, Dbxref dbxref) {
        this.organism = organism;
        this.dbxref = dbxref;
    }

   
    // Property accessors

    public Integer getOrganismDbxrefId() {
        return this.organismDbxrefId;
    }
    
    public void setOrganismDbxrefId(Integer organismDbxrefId) {
        this.organismDbxrefId = organismDbxrefId;
    }

    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }
   








}