package org.nescent.heliconius.hibernate;



/**
 * Organismprop generated by MyEclipse - Hibernate Tools
 */

public class Organismprop  implements java.io.Serializable {


    // Fields    

     private Integer organismpropId;
     private Organism organism;
     private Cvterm cvterm;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public Organismprop() {
    }

	/** minimal constructor */
    public Organismprop(Organism organism, Cvterm cvterm, Integer rank) {
        this.organism = organism;
        this.cvterm = cvterm;
        this.rank = rank;
    }
    
    /** full constructor */
    public Organismprop(Organism organism, Cvterm cvterm, String value, Integer rank) {
        this.organism = organism;
        this.cvterm = cvterm;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getOrganismpropId() {
        return this.organismpropId;
    }
    
    public void setOrganismpropId(Integer organismpropId) {
        this.organismpropId = organismpropId;
    }

    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}