package org.nescent.heliconius.hibernate;



/**
 * Phenstatement generated by MyEclipse - Hibernate Tools
 */

public class Phenstatement  implements java.io.Serializable {


    // Fields    

     private Integer phenstatementId;
     private Cvterm cvterm;
     private Environment environment;
     private Pub pub;
     private Phenotype phenotype;
     private Genotype genotype;


    // Constructors

    /** default constructor */
    public Phenstatement() {
    }

    
    /** full constructor */
    public Phenstatement(Cvterm cvterm, Environment environment, Pub pub, Phenotype phenotype, Genotype genotype) {
        this.cvterm = cvterm;
        this.environment = environment;
        this.pub = pub;
        this.phenotype = phenotype;
        this.genotype = genotype;
    }

   
    // Property accessors

    public Integer getPhenstatementId() {
        return this.phenstatementId;
    }
    
    public void setPhenstatementId(Integer phenstatementId) {
        this.phenstatementId = phenstatementId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Environment getEnvironment() {
        return this.environment;
    }
    
    public void setEnvironment(Environment environment) {
        this.environment = environment;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Phenotype getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(Phenotype phenotype) {
        this.phenotype = phenotype;
    }

    public Genotype getGenotype() {
        return this.genotype;
    }
    
    public void setGenotype(Genotype genotype) {
        this.genotype = genotype;
    }
   








}