package org.nescent.heliconius.hibernate;



/**
 * PhenotypeComparison generated by MyEclipse - Hibernate Tools
 */

public class PhenotypeComparison  implements java.io.Serializable {


    // Fields    

     private Integer phenotypeComparisonId;
     private Environment environmentByEnvironment1Id;
     private Environment environmentByEnvironment2Id;
     private Cvterm cvterm;
     private Phenotype phenotypeByPhenotype2Id;
     private Genotype genotypeByGenotype1Id;
     private Pub pub;
     private Genotype genotypeByGenotype2Id;
     private Phenotype phenotypeByPhenotype1Id;


    // Constructors

    /** default constructor */
    public PhenotypeComparison() {
    }

	/** minimal constructor */
    public PhenotypeComparison(Environment environmentByEnvironment1Id, Environment environmentByEnvironment2Id, Cvterm cvterm, Genotype genotypeByGenotype1Id, Pub pub, Genotype genotypeByGenotype2Id, Phenotype phenotypeByPhenotype1Id) {
        this.environmentByEnvironment1Id = environmentByEnvironment1Id;
        this.environmentByEnvironment2Id = environmentByEnvironment2Id;
        this.cvterm = cvterm;
        this.genotypeByGenotype1Id = genotypeByGenotype1Id;
        this.pub = pub;
        this.genotypeByGenotype2Id = genotypeByGenotype2Id;
        this.phenotypeByPhenotype1Id = phenotypeByPhenotype1Id;
    }
    
    /** full constructor */
    public PhenotypeComparison(Environment environmentByEnvironment1Id, Environment environmentByEnvironment2Id, Cvterm cvterm, Phenotype phenotypeByPhenotype2Id, Genotype genotypeByGenotype1Id, Pub pub, Genotype genotypeByGenotype2Id, Phenotype phenotypeByPhenotype1Id) {
        this.environmentByEnvironment1Id = environmentByEnvironment1Id;
        this.environmentByEnvironment2Id = environmentByEnvironment2Id;
        this.cvterm = cvterm;
        this.phenotypeByPhenotype2Id = phenotypeByPhenotype2Id;
        this.genotypeByGenotype1Id = genotypeByGenotype1Id;
        this.pub = pub;
        this.genotypeByGenotype2Id = genotypeByGenotype2Id;
        this.phenotypeByPhenotype1Id = phenotypeByPhenotype1Id;
    }

   
    // Property accessors

    public Integer getPhenotypeComparisonId() {
        return this.phenotypeComparisonId;
    }
    
    public void setPhenotypeComparisonId(Integer phenotypeComparisonId) {
        this.phenotypeComparisonId = phenotypeComparisonId;
    }

    public Environment getEnvironmentByEnvironment1Id() {
        return this.environmentByEnvironment1Id;
    }
    
    public void setEnvironmentByEnvironment1Id(Environment environmentByEnvironment1Id) {
        this.environmentByEnvironment1Id = environmentByEnvironment1Id;
    }

    public Environment getEnvironmentByEnvironment2Id() {
        return this.environmentByEnvironment2Id;
    }
    
    public void setEnvironmentByEnvironment2Id(Environment environmentByEnvironment2Id) {
        this.environmentByEnvironment2Id = environmentByEnvironment2Id;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Phenotype getPhenotypeByPhenotype2Id() {
        return this.phenotypeByPhenotype2Id;
    }
    
    public void setPhenotypeByPhenotype2Id(Phenotype phenotypeByPhenotype2Id) {
        this.phenotypeByPhenotype2Id = phenotypeByPhenotype2Id;
    }

    public Genotype getGenotypeByGenotype1Id() {
        return this.genotypeByGenotype1Id;
    }
    
    public void setGenotypeByGenotype1Id(Genotype genotypeByGenotype1Id) {
        this.genotypeByGenotype1Id = genotypeByGenotype1Id;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Genotype getGenotypeByGenotype2Id() {
        return this.genotypeByGenotype2Id;
    }
    
    public void setGenotypeByGenotype2Id(Genotype genotypeByGenotype2Id) {
        this.genotypeByGenotype2Id = genotypeByGenotype2Id;
    }

    public Phenotype getPhenotypeByPhenotype1Id() {
        return this.phenotypeByPhenotype1Id;
    }
    
    public void setPhenotypeByPhenotype1Id(Phenotype phenotypeByPhenotype1Id) {
        this.phenotypeByPhenotype1Id = phenotypeByPhenotype1Id;
    }
   








}