package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Phenotype generated by MyEclipse - Hibernate Tools
 */

public class Phenotype  implements java.io.Serializable {


    // Fields    

     private Integer phenotypeId;
     private Cvterm cvtermByAttrId;
     private Cvterm cvtermByCvalueId;
     private Cvterm cvtermByObservableId;
     private Cvterm cvtermByAssayId;
     private String uniquename;
     private String value;
     private Set stockPhenotypes = new HashSet(0);
     private Set individualPhenotypes = new HashSet(0);
     private Set phenotypeCvterms = new HashSet(0);
     private Set phenotypeComparisonsForPhenotype2Id = new HashSet(0);
     private Set phenstatements = new HashSet(0);
     private Set phenotypeComparisonsForPhenotype1Id = new HashSet(0);
     private Set featurePhenotypes = new HashSet(0);
     private Set biotypePhenotypes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Phenotype() {
    }

	/** minimal constructor */
    public Phenotype(String uniquename) {
        this.uniquename = uniquename;
    }
    
    /** full constructor */
    public Phenotype(Cvterm cvtermByAttrId, Cvterm cvtermByCvalueId, Cvterm cvtermByObservableId, Cvterm cvtermByAssayId, String uniquename, String value, Set stockPhenotypes, Set individualPhenotypes, Set phenotypeCvterms, Set phenotypeComparisonsForPhenotype2Id, Set phenstatements, Set phenotypeComparisonsForPhenotype1Id, Set featurePhenotypes, Set biotypePhenotypes) {
        this.cvtermByAttrId = cvtermByAttrId;
        this.cvtermByCvalueId = cvtermByCvalueId;
        this.cvtermByObservableId = cvtermByObservableId;
        this.cvtermByAssayId = cvtermByAssayId;
        this.uniquename = uniquename;
        this.value = value;
        this.stockPhenotypes = stockPhenotypes;
        this.individualPhenotypes = individualPhenotypes;
        this.phenotypeCvterms = phenotypeCvterms;
        this.phenotypeComparisonsForPhenotype2Id = phenotypeComparisonsForPhenotype2Id;
        this.phenstatements = phenstatements;
        this.phenotypeComparisonsForPhenotype1Id = phenotypeComparisonsForPhenotype1Id;
        this.featurePhenotypes = featurePhenotypes;
        this.biotypePhenotypes = biotypePhenotypes;
    }

   
    // Property accessors

    public Integer getPhenotypeId() {
        return this.phenotypeId;
    }
    
    public void setPhenotypeId(Integer phenotypeId) {
        this.phenotypeId = phenotypeId;
    }

    public Cvterm getCvtermByAttrId() {
        return this.cvtermByAttrId;
    }
    
    public void setCvtermByAttrId(Cvterm cvtermByAttrId) {
        this.cvtermByAttrId = cvtermByAttrId;
    }

    public Cvterm getCvtermByCvalueId() {
        return this.cvtermByCvalueId;
    }
    
    public void setCvtermByCvalueId(Cvterm cvtermByCvalueId) {
        this.cvtermByCvalueId = cvtermByCvalueId;
    }

    public Cvterm getCvtermByObservableId() {
        return this.cvtermByObservableId;
    }
    
    public void setCvtermByObservableId(Cvterm cvtermByObservableId) {
        this.cvtermByObservableId = cvtermByObservableId;
    }

    public Cvterm getCvtermByAssayId() {
        return this.cvtermByAssayId;
    }
    
    public void setCvtermByAssayId(Cvterm cvtermByAssayId) {
        this.cvtermByAssayId = cvtermByAssayId;
    }

    public String getUniquename() {
        return this.uniquename;
    }
    
    public void setUniquename(String uniquename) {
        this.uniquename = uniquename;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Set getStockPhenotypes() {
        return this.stockPhenotypes;
    }
    
    public void setStockPhenotypes(Set stockPhenotypes) {
        this.stockPhenotypes = stockPhenotypes;
    }

    public Set getIndividualPhenotypes() {
        return this.individualPhenotypes;
    }
    
    public void setIndividualPhenotypes(Set individualPhenotypes) {
        this.individualPhenotypes = individualPhenotypes;
    }

    public Set getPhenotypeCvterms() {
        return this.phenotypeCvterms;
    }
    
    public void setPhenotypeCvterms(Set phenotypeCvterms) {
        this.phenotypeCvterms = phenotypeCvterms;
    }

    public Set getPhenotypeComparisonsForPhenotype2Id() {
        return this.phenotypeComparisonsForPhenotype2Id;
    }
    
    public void setPhenotypeComparisonsForPhenotype2Id(Set phenotypeComparisonsForPhenotype2Id) {
        this.phenotypeComparisonsForPhenotype2Id = phenotypeComparisonsForPhenotype2Id;
    }

    public Set getPhenstatements() {
        return this.phenstatements;
    }
    
    public void setPhenstatements(Set phenstatements) {
        this.phenstatements = phenstatements;
    }

    public Set getPhenotypeComparisonsForPhenotype1Id() {
        return this.phenotypeComparisonsForPhenotype1Id;
    }
    
    public void setPhenotypeComparisonsForPhenotype1Id(Set phenotypeComparisonsForPhenotype1Id) {
        this.phenotypeComparisonsForPhenotype1Id = phenotypeComparisonsForPhenotype1Id;
    }

    public Set getFeaturePhenotypes() {
        return this.featurePhenotypes;
    }
    
    public void setFeaturePhenotypes(Set featurePhenotypes) {
        this.featurePhenotypes = featurePhenotypes;
    }

    public Set getBiotypePhenotypes() {
        return this.biotypePhenotypes;
    }
    
    public void setBiotypePhenotypes(Set biotypePhenotypes) {
        this.biotypePhenotypes = biotypePhenotypes;
    }
   








}