package org.nescent.heliconius.hibernate;



/**
 * Phendesc generated by MyEclipse - Hibernate Tools
 */

public class Phendesc  implements java.io.Serializable {


    // Fields    

     private Integer phendescId;
     private Cvterm cvterm;
     private Environment environment;
     private Pub pub;
     private Genotype genotype;
     private String description;


    // Constructors

    /** default constructor */
    public Phendesc() {
    }

    
    /** full constructor */
    public Phendesc(Cvterm cvterm, Environment environment, Pub pub, Genotype genotype, String description) {
        this.cvterm = cvterm;
        this.environment = environment;
        this.pub = pub;
        this.genotype = genotype;
        this.description = description;
    }

   
    // Property accessors

    public Integer getPhendescId() {
        return this.phendescId;
    }
    
    public void setPhendescId(Integer phendescId) {
        this.phendescId = phendescId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Environment getEnvironment() {
        return this.environment;
    }
    
    public void setEnvironment(Environment environment) {
        this.environment = environment;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Genotype getGenotype() {
        return this.genotype;
    }
    
    public void setGenotype(Genotype genotype) {
        this.genotype = genotype;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}