package org.nescent.heliconius.hibernate;



/**
 * PhenotypeCvterm generated by MyEclipse - Hibernate Tools
 */

public class PhenotypeCvterm  implements java.io.Serializable {


    // Fields    

     private Integer phenotypeCvtermId;
     private Cvterm cvterm;
     private Phenotype phenotype;


    // Constructors

    /** default constructor */
    public PhenotypeCvterm() {
    }

    
    /** full constructor */
    public PhenotypeCvterm(Cvterm cvterm, Phenotype phenotype) {
        this.cvterm = cvterm;
        this.phenotype = phenotype;
    }

   
    // Property accessors

    public Integer getPhenotypeCvtermId() {
        return this.phenotypeCvtermId;
    }
    
    public void setPhenotypeCvtermId(Integer phenotypeCvtermId) {
        this.phenotypeCvtermId = phenotypeCvtermId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Phenotype getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(Phenotype phenotype) {
        this.phenotype = phenotype;
    }
   








}