package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Ptassay generated by MyEclipse - Hibernate Tools
 */

public class Ptassay  implements java.io.Serializable {


    // Fields    

     private Integer ptassayId;
     private String name;
     private Set biotypePhenotypes = new HashSet(0);
     private Set ptassayprops = new HashSet(0);
     private Set individualPhenotypes = new HashSet(0);
     private Set stockPhenotypes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Ptassay() {
    }

	/** minimal constructor */
    public Ptassay(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public Ptassay(String name, Set biotypePhenotypes, Set ptassayprops, Set individualPhenotypes, Set stockPhenotypes) {
        this.name = name;
        this.biotypePhenotypes = biotypePhenotypes;
        this.ptassayprops = ptassayprops;
        this.individualPhenotypes = individualPhenotypes;
        this.stockPhenotypes = stockPhenotypes;
    }

   
    // Property accessors

    public Integer getPtassayId() {
        return this.ptassayId;
    }
    
    public void setPtassayId(Integer ptassayId) {
        this.ptassayId = ptassayId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getBiotypePhenotypes() {
        return this.biotypePhenotypes;
    }
    
    public void setBiotypePhenotypes(Set biotypePhenotypes) {
        this.biotypePhenotypes = biotypePhenotypes;
    }

    public Set getPtassayprops() {
        return this.ptassayprops;
    }
    
    public void setPtassayprops(Set ptassayprops) {
        this.ptassayprops = ptassayprops;
    }

    public Set getIndividualPhenotypes() {
        return this.individualPhenotypes;
    }
    
    public void setIndividualPhenotypes(Set individualPhenotypes) {
        this.individualPhenotypes = individualPhenotypes;
    }

    public Set getStockPhenotypes() {
        return this.stockPhenotypes;
    }
    
    public void setStockPhenotypes(Set stockPhenotypes) {
        this.stockPhenotypes = stockPhenotypes;
    }
   








}