package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Pub generated by MyEclipse - Hibernate Tools
 */

public class Pub  implements java.io.Serializable {


    // Fields    

     private Integer pubId;
     private Cvterm cvterm;
     private String title;
     private String volumetitle;
     private String volume;
     private String seriesName;
     private String issue;
     private String pyear;
     private String pages;
     private String miniref;
     private String uniquename;
     private Byte isObsolete;
     private String publisher;
     private String pubplace;
     private Set pubauthors = new HashSet(0);
     private Set phenstatements = new HashSet(0);
     private Set pubRelationshipsForObjectId = new HashSet(0);
     private Set biotypePhenotypes = new HashSet(0);
     private Set stockPhenotypes = new HashSet(0);
     private Set pubDbxrefs = new HashSet(0);
     private Set featureCvterms = new HashSet(0);
     private Set featureRelationshipPubs = new HashSet(0);
     private Set phendescs = new HashSet(0);
     private Set featurePubs = new HashSet(0);
     private Set phenotypeComparisons = new HashSet(0);
     private Set featurepropPubs = new HashSet(0);
     private Set individualPhenotypes = new HashSet(0);
     private Set featureSynonyms = new HashSet(0);
     private Set featureCvtermPubs = new HashSet(0);
     private Set featureRelationshippropPubs = new HashSet(0);
     private Set pubprops = new HashSet(0);
     private Set pubRelationshipsForSubjectId = new HashSet(0);
     private Set gtexperiments = new HashSet(0);
     private Set featurelocPubs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Pub() {
    }

	/** minimal constructor */
    public Pub(Cvterm cvterm, String uniquename) {
        this.cvterm = cvterm;
        this.uniquename = uniquename;
    }
    
    /** full constructor */
    public Pub(Cvterm cvterm, String title, String volumetitle, String volume, String seriesName, String issue, String pyear, String pages, String miniref, String uniquename, Byte isObsolete, String publisher, String pubplace, Set pubauthors, Set phenstatements, Set pubRelationshipsForObjectId, Set biotypePhenotypes, Set stockPhenotypes, Set pubDbxrefs, Set featureCvterms, Set featureRelationshipPubs, Set phendescs, Set featurePubs, Set phenotypeComparisons, Set featurepropPubs, Set individualPhenotypes, Set featureSynonyms, Set featureCvtermPubs, Set featureRelationshippropPubs, Set pubprops, Set pubRelationshipsForSubjectId, Set gtexperiments, Set featurelocPubs) {
        this.cvterm = cvterm;
        this.title = title;
        this.volumetitle = volumetitle;
        this.volume = volume;
        this.seriesName = seriesName;
        this.issue = issue;
        this.pyear = pyear;
        this.pages = pages;
        this.miniref = miniref;
        this.uniquename = uniquename;
        this.isObsolete = isObsolete;
        this.publisher = publisher;
        this.pubplace = pubplace;
        this.pubauthors = pubauthors;
        this.phenstatements = phenstatements;
        this.pubRelationshipsForObjectId = pubRelationshipsForObjectId;
        this.biotypePhenotypes = biotypePhenotypes;
        this.stockPhenotypes = stockPhenotypes;
        this.pubDbxrefs = pubDbxrefs;
        this.featureCvterms = featureCvterms;
        this.featureRelationshipPubs = featureRelationshipPubs;
        this.phendescs = phendescs;
        this.featurePubs = featurePubs;
        this.phenotypeComparisons = phenotypeComparisons;
        this.featurepropPubs = featurepropPubs;
        this.individualPhenotypes = individualPhenotypes;
        this.featureSynonyms = featureSynonyms;
        this.featureCvtermPubs = featureCvtermPubs;
        this.featureRelationshippropPubs = featureRelationshippropPubs;
        this.pubprops = pubprops;
        this.pubRelationshipsForSubjectId = pubRelationshipsForSubjectId;
        this.gtexperiments = gtexperiments;
        this.featurelocPubs = featurelocPubs;
    }

   
    // Property accessors

    public Integer getPubId() {
        return this.pubId;
    }
    
    public void setPubId(Integer pubId) {
        this.pubId = pubId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getVolumetitle() {
        return this.volumetitle;
    }
    
    public void setVolumetitle(String volumetitle) {
        this.volumetitle = volumetitle;
    }

    public String getVolume() {
        return this.volume;
    }
    
    public void setVolume(String volume) {
        this.volume = volume;
    }

    public String getSeriesName() {
        return this.seriesName;
    }
    
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName;
    }

    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    public String getPyear() {
        return this.pyear;
    }
    
    public void setPyear(String pyear) {
        this.pyear = pyear;
    }

    public String getPages() {
        return this.pages;
    }
    
    public void setPages(String pages) {
        this.pages = pages;
    }

    public String getMiniref() {
        return this.miniref;
    }
    
    public void setMiniref(String miniref) {
        this.miniref = miniref;
    }

    public String getUniquename() {
        return this.uniquename;
    }
    
    public void setUniquename(String uniquename) {
        this.uniquename = uniquename;
    }

    public Byte getIsObsolete() {
        return this.isObsolete;
    }
    
    public void setIsObsolete(Byte isObsolete) {
        this.isObsolete = isObsolete;
    }

    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getPubplace() {
        return this.pubplace;
    }
    
    public void setPubplace(String pubplace) {
        this.pubplace = pubplace;
    }

    public Set getPubauthors() {
        return this.pubauthors;
    }
    
    public void setPubauthors(Set pubauthors) {
        this.pubauthors = pubauthors;
    }

    public Set getPhenstatements() {
        return this.phenstatements;
    }
    
    public void setPhenstatements(Set phenstatements) {
        this.phenstatements = phenstatements;
    }

    public Set getPubRelationshipsForObjectId() {
        return this.pubRelationshipsForObjectId;
    }
    
    public void setPubRelationshipsForObjectId(Set pubRelationshipsForObjectId) {
        this.pubRelationshipsForObjectId = pubRelationshipsForObjectId;
    }

    public Set getBiotypePhenotypes() {
        return this.biotypePhenotypes;
    }
    
    public void setBiotypePhenotypes(Set biotypePhenotypes) {
        this.biotypePhenotypes = biotypePhenotypes;
    }

    public Set getStockPhenotypes() {
        return this.stockPhenotypes;
    }
    
    public void setStockPhenotypes(Set stockPhenotypes) {
        this.stockPhenotypes = stockPhenotypes;
    }

    public Set getPubDbxrefs() {
        return this.pubDbxrefs;
    }
    
    public void setPubDbxrefs(Set pubDbxrefs) {
        this.pubDbxrefs = pubDbxrefs;
    }

    public Set getFeatureCvterms() {
        return this.featureCvterms;
    }
    
    public void setFeatureCvterms(Set featureCvterms) {
        this.featureCvterms = featureCvterms;
    }

    public Set getFeatureRelationshipPubs() {
        return this.featureRelationshipPubs;
    }
    
    public void setFeatureRelationshipPubs(Set featureRelationshipPubs) {
        this.featureRelationshipPubs = featureRelationshipPubs;
    }

    public Set getPhendescs() {
        return this.phendescs;
    }
    
    public void setPhendescs(Set phendescs) {
        this.phendescs = phendescs;
    }

    public Set getFeaturePubs() {
        return this.featurePubs;
    }
    
    public void setFeaturePubs(Set featurePubs) {
        this.featurePubs = featurePubs;
    }

    public Set getPhenotypeComparisons() {
        return this.phenotypeComparisons;
    }
    
    public void setPhenotypeComparisons(Set phenotypeComparisons) {
        this.phenotypeComparisons = phenotypeComparisons;
    }

    public Set getFeaturepropPubs() {
        return this.featurepropPubs;
    }
    
    public void setFeaturepropPubs(Set featurepropPubs) {
        this.featurepropPubs = featurepropPubs;
    }

    public Set getIndividualPhenotypes() {
        return this.individualPhenotypes;
    }
    
    public void setIndividualPhenotypes(Set individualPhenotypes) {
        this.individualPhenotypes = individualPhenotypes;
    }

    public Set getFeatureSynonyms() {
        return this.featureSynonyms;
    }
    
    public void setFeatureSynonyms(Set featureSynonyms) {
        this.featureSynonyms = featureSynonyms;
    }

    public Set getFeatureCvtermPubs() {
        return this.featureCvtermPubs;
    }
    
    public void setFeatureCvtermPubs(Set featureCvtermPubs) {
        this.featureCvtermPubs = featureCvtermPubs;
    }

    public Set getFeatureRelationshippropPubs() {
        return this.featureRelationshippropPubs;
    }
    
    public void setFeatureRelationshippropPubs(Set featureRelationshippropPubs) {
        this.featureRelationshippropPubs = featureRelationshippropPubs;
    }

    public Set getPubprops() {
        return this.pubprops;
    }
    
    public void setPubprops(Set pubprops) {
        this.pubprops = pubprops;
    }

    public Set getPubRelationshipsForSubjectId() {
        return this.pubRelationshipsForSubjectId;
    }
    
    public void setPubRelationshipsForSubjectId(Set pubRelationshipsForSubjectId) {
        this.pubRelationshipsForSubjectId = pubRelationshipsForSubjectId;
    }

    public Set getGtexperiments() {
        return this.gtexperiments;
    }
    
    public void setGtexperiments(Set gtexperiments) {
        this.gtexperiments = gtexperiments;
    }

    public Set getFeaturelocPubs() {
        return this.featurelocPubs;
    }
    
    public void setFeaturelocPubs(Set featurelocPubs) {
        this.featurelocPubs = featurelocPubs;
    }
   








}