package org.nescent.heliconius.hibernate;



/**
 * PubDbxref generated by MyEclipse - Hibernate Tools
 */

public class PubDbxref  implements java.io.Serializable {


    // Fields    

     private Integer pubDbxrefId;
     private Dbxref dbxref;
     private Pub pub;
     private Byte isCurrent;


    // Constructors

    /** default constructor */
    public PubDbxref() {
    }

    
    /** full constructor */
    public PubDbxref(Dbxref dbxref, Pub pub, Byte isCurrent) {
        this.dbxref = dbxref;
        this.pub = pub;
        this.isCurrent = isCurrent;
    }

   
    // Property accessors

    public Integer getPubDbxrefId() {
        return this.pubDbxrefId;
    }
    
    public void setPubDbxrefId(Integer pubDbxrefId) {
        this.pubDbxrefId = pubDbxrefId;
    }

    public Dbxref getDbxref() {
        return this.dbxref;
    }
    
    public void setDbxref(Dbxref dbxref) {
        this.dbxref = dbxref;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Byte getIsCurrent() {
        return this.isCurrent;
    }
    
    public void setIsCurrent(Byte isCurrent) {
        this.isCurrent = isCurrent;
    }
   








}