package org.nescent.heliconius.hibernate;



/**
 * Pubprop generated by MyEclipse - Hibernate Tools
 */

public class Pubprop  implements java.io.Serializable {


    // Fields    

     private Integer pubpropId;
     private Cvterm cvterm;
     private Pub pub;
     private String value;
     private Integer rank;


    // Constructors

    /** default constructor */
    public Pubprop() {
    }

	/** minimal constructor */
    public Pubprop(Cvterm cvterm, Pub pub, String value) {
        this.cvterm = cvterm;
        this.pub = pub;
        this.value = value;
    }
    
    /** full constructor */
    public Pubprop(Cvterm cvterm, Pub pub, String value, Integer rank) {
        this.cvterm = cvterm;
        this.pub = pub;
        this.value = value;
        this.rank = rank;
    }

   
    // Property accessors

    public Integer getPubpropId() {
        return this.pubpropId;
    }
    
    public void setPubpropId(Integer pubpropId) {
        this.pubpropId = pubpropId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
   








}