package org.nescent.heliconius.hibernate;



/**
 * PubRelationship generated by MyEclipse - Hibernate Tools
 */

public class PubRelationship  implements java.io.Serializable {


    // Fields    

     private Integer pubRelationshipId;
     private Pub pubBySubjectId;
     private Pub pubByObjectId;
     private Cvterm cvterm;


    // Constructors

    /** default constructor */
    public PubRelationship() {
    }

    
    /** full constructor */
    public PubRelationship(Pub pubBySubjectId, Pub pubByObjectId, Cvterm cvterm) {
        this.pubBySubjectId = pubBySubjectId;
        this.pubByObjectId = pubByObjectId;
        this.cvterm = cvterm;
    }

   
    // Property accessors

    public Integer getPubRelationshipId() {
        return this.pubRelationshipId;
    }
    
    public void setPubRelationshipId(Integer pubRelationshipId) {
        this.pubRelationshipId = pubRelationshipId;
    }

    public Pub getPubBySubjectId() {
        return this.pubBySubjectId;
    }
    
    public void setPubBySubjectId(Pub pubBySubjectId) {
        this.pubBySubjectId = pubBySubjectId;
    }

    public Pub getPubByObjectId() {
        return this.pubByObjectId;
    }
    
    public void setPubByObjectId(Pub pubByObjectId) {
        this.pubByObjectId = pubByObjectId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }
   








}