package org.nescent.heliconius.hibernate;



/**
 * ReagentRelationship generated by MyEclipse - Hibernate Tools
 */

public class ReagentRelationship  implements java.io.Serializable {


    // Fields    

     private Integer reagentRelationshipId;
     private Reagent reagentByObjectReagentId;
     private Cvterm cvterm;
     private Reagent reagentBySubjectReagentId;


    // Constructors

    /** default constructor */
    public ReagentRelationship() {
    }

    
    /** full constructor */
    public ReagentRelationship(Reagent reagentByObjectReagentId, Cvterm cvterm, Reagent reagentBySubjectReagentId) {
        this.reagentByObjectReagentId = reagentByObjectReagentId;
        this.cvterm = cvterm;
        this.reagentBySubjectReagentId = reagentBySubjectReagentId;
    }

   
    // Property accessors

    public Integer getReagentRelationshipId() {
        return this.reagentRelationshipId;
    }
    
    public void setReagentRelationshipId(Integer reagentRelationshipId) {
        this.reagentRelationshipId = reagentRelationshipId;
    }

    public Reagent getReagentByObjectReagentId() {
        return this.reagentByObjectReagentId;
    }
    
    public void setReagentByObjectReagentId(Reagent reagentByObjectReagentId) {
        this.reagentByObjectReagentId = reagentByObjectReagentId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Reagent getReagentBySubjectReagentId() {
        return this.reagentBySubjectReagentId;
    }
    
    public void setReagentBySubjectReagentId(Reagent reagentBySubjectReagentId) {
        this.reagentBySubjectReagentId = reagentBySubjectReagentId;
    }
   








}