package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Reagent generated by MyEclipse - Hibernate Tools
 */

public class Reagent  implements java.io.Serializable {


    // Fields    

     private Integer reagentId;
     private Cvterm cvterm;
     private Feature feature;
     private String name;
     private Set reagentRelationshipsForObjectReagentId = new HashSet(0);
     private Set reagentRelationshipsForSubjectReagentId = new HashSet(0);
     private Set reagentprops = new HashSet(0);
     private Set gtassayReagents = new HashSet(0);


    // Constructors

    /** default constructor */
    public Reagent() {
    }

	/** minimal constructor */
    public Reagent(Cvterm cvterm, String name) {
        this.cvterm = cvterm;
        this.name = name;
    }
    
    /** full constructor */
    public Reagent(Cvterm cvterm, Feature feature, String name, Set reagentRelationshipsForObjectReagentId, Set reagentRelationshipsForSubjectReagentId, Set reagentprops, Set gtassayReagents) {
        this.cvterm = cvterm;
        this.feature = feature;
        this.name = name;
        this.reagentRelationshipsForObjectReagentId = reagentRelationshipsForObjectReagentId;
        this.reagentRelationshipsForSubjectReagentId = reagentRelationshipsForSubjectReagentId;
        this.reagentprops = reagentprops;
        this.gtassayReagents = gtassayReagents;
    }

   
    // Property accessors

    public Integer getReagentId() {
        return this.reagentId;
    }
    
    public void setReagentId(Integer reagentId) {
        this.reagentId = reagentId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getReagentRelationshipsForObjectReagentId() {
        return this.reagentRelationshipsForObjectReagentId;
    }
    
    public void setReagentRelationshipsForObjectReagentId(Set reagentRelationshipsForObjectReagentId) {
        this.reagentRelationshipsForObjectReagentId = reagentRelationshipsForObjectReagentId;
    }

    public Set getReagentRelationshipsForSubjectReagentId() {
        return this.reagentRelationshipsForSubjectReagentId;
    }
    
    public void setReagentRelationshipsForSubjectReagentId(Set reagentRelationshipsForSubjectReagentId) {
        this.reagentRelationshipsForSubjectReagentId = reagentRelationshipsForSubjectReagentId;
    }

    public Set getReagentprops() {
        return this.reagentprops;
    }
    
    public void setReagentprops(Set reagentprops) {
        this.reagentprops = reagentprops;
    }

    public Set getGtassayReagents() {
        return this.gtassayReagents;
    }
    
    public void setGtassayReagents(Set gtassayReagents) {
        this.gtassayReagents = gtassayReagents;
    }
   








}