package org.nescent.heliconius.hibernate;



/**
 * SpecimenImage generated by MyEclipse - Hibernate Tools
 */

public class SpecimenImage  implements java.io.Serializable {


    // Fields    

     private Integer specimenImageId;
     private Specimen specimen;
     private Image image;


    // Constructors

    /** default constructor */
    public SpecimenImage() {
    }

    
    /** full constructor */
    public SpecimenImage(Specimen specimen, Image image) {
        this.specimen = specimen;
        this.image = image;
    }

   
    // Property accessors

    public Integer getSpecimenImageId() {
        return this.specimenImageId;
    }
    
    public void setSpecimenImageId(Integer specimenImageId) {
        this.specimenImageId = specimenImageId;
    }

    public Specimen getSpecimen() {
        return this.specimen;
    }
    
    public void setSpecimen(Specimen specimen) {
        this.specimen = specimen;
    }

    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }
   








}