package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * StockPhenotype generated by MyEclipse - Hibernate Tools
 */

public class StockPhenotype  implements java.io.Serializable {


    // Fields    

     private Integer stockPhenotypeId;
     private Stock stock;
     private Contact contact;
     private Ptassay ptassay;
     private Pub pub;
     private Phenotype phenotype;
     private Date assayDate;
     private String notes;
     private Set stockPhenotypeProjects = new HashSet(0);


    // Constructors

    /** default constructor */
    public StockPhenotype() {
    }

	/** minimal constructor */
    public StockPhenotype(Stock stock) {
        this.stock = stock;
    }
    
    /** full constructor */
    public StockPhenotype(Stock stock, Contact contact, Ptassay ptassay, Pub pub, Phenotype phenotype, Date assayDate, String notes, Set stockPhenotypeProjects) {
        this.stock = stock;
        this.contact = contact;
        this.ptassay = ptassay;
        this.pub = pub;
        this.phenotype = phenotype;
        this.assayDate = assayDate;
        this.notes = notes;
        this.stockPhenotypeProjects = stockPhenotypeProjects;
    }

   
    // Property accessors

    public Integer getStockPhenotypeId() {
        return this.stockPhenotypeId;
    }
    
    public void setStockPhenotypeId(Integer stockPhenotypeId) {
        this.stockPhenotypeId = stockPhenotypeId;
    }

    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Ptassay getPtassay() {
        return this.ptassay;
    }
    
    public void setPtassay(Ptassay ptassay) {
        this.ptassay = ptassay;
    }

    public Pub getPub() {
        return this.pub;
    }
    
    public void setPub(Pub pub) {
        this.pub = pub;
    }

    public Phenotype getPhenotype() {
        return this.phenotype;
    }
    
    public void setPhenotype(Phenotype phenotype) {
        this.phenotype = phenotype;
    }

    public Date getAssayDate() {
        return this.assayDate;
    }
    
    public void setAssayDate(Date assayDate) {
        this.assayDate = assayDate;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set getStockPhenotypeProjects() {
        return this.stockPhenotypeProjects;
    }
    
    public void setStockPhenotypeProjects(Set stockPhenotypeProjects) {
        this.stockPhenotypeProjects = stockPhenotypeProjects;
    }
   








}