package org.nescent.heliconius.hibernate;



/**
 * StockPhenotypeProject generated by MyEclipse - Hibernate Tools
 */

public class StockPhenotypeProject  implements java.io.Serializable {


    // Fields    

     private Integer stockPhenotypeProjectId;
     private StockPhenotype stockPhenotype;
     private Project project;


    // Constructors

    /** default constructor */
    public StockPhenotypeProject() {
    }

    
    /** full constructor */
    public StockPhenotypeProject(StockPhenotype stockPhenotype, Project project) {
        this.stockPhenotype = stockPhenotype;
        this.project = project;
    }

   
    // Property accessors

    public Integer getStockPhenotypeProjectId() {
        return this.stockPhenotypeProjectId;
    }
    
    public void setStockPhenotypeProjectId(Integer stockPhenotypeProjectId) {
        this.stockPhenotypeProjectId = stockPhenotypeProjectId;
    }

    public StockPhenotype getStockPhenotype() {
        return this.stockPhenotype;
    }
    
    public void setStockPhenotype(StockPhenotype stockPhenotype) {
        this.stockPhenotype = stockPhenotype;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
   








}