package org.nescent.heliconius.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Stock generated by MyEclipse - Hibernate Tools
 */

public class Stock  implements java.io.Serializable {


    // Fields    

     private Integer stockId;
     private Biotype biotypeByPaternalBiotypeId;
     private Biotype biotypeByMaternalBiotypeId;
     private Contact contact;
     private Geolocation geolocation;
     private Biotype biotypeByBiotypeId;
     private String name;
     private String description;
     private Date dateCreated;
     private Set individuals = new HashSet(0);
     private Set stockPhenotypes = new HashSet(0);


    // Constructors

    /** default constructor */
    public Stock() {
    }

	/** minimal constructor */
    public Stock(Biotype biotypeByBiotypeId, String name) {
        this.biotypeByBiotypeId = biotypeByBiotypeId;
        this.name = name;
    }
    
    /** full constructor */
    public Stock(Biotype biotypeByPaternalBiotypeId, Biotype biotypeByMaternalBiotypeId, Contact contact, Geolocation geolocation, Biotype biotypeByBiotypeId, String name, String description, Date dateCreated, Set individuals, Set stockPhenotypes) {
        this.biotypeByPaternalBiotypeId = biotypeByPaternalBiotypeId;
        this.biotypeByMaternalBiotypeId = biotypeByMaternalBiotypeId;
        this.contact = contact;
        this.geolocation = geolocation;
        this.biotypeByBiotypeId = biotypeByBiotypeId;
        this.name = name;
        this.description = description;
        this.dateCreated = dateCreated;
        this.individuals = individuals;
        this.stockPhenotypes = stockPhenotypes;
    }

   
    // Property accessors

    public Integer getStockId() {
        return this.stockId;
    }
    
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    public Biotype getBiotypeByPaternalBiotypeId() {
        return this.biotypeByPaternalBiotypeId;
    }
    
    public void setBiotypeByPaternalBiotypeId(Biotype biotypeByPaternalBiotypeId) {
        this.biotypeByPaternalBiotypeId = biotypeByPaternalBiotypeId;
    }

    public Biotype getBiotypeByMaternalBiotypeId() {
        return this.biotypeByMaternalBiotypeId;
    }
    
    public void setBiotypeByMaternalBiotypeId(Biotype biotypeByMaternalBiotypeId) {
        this.biotypeByMaternalBiotypeId = biotypeByMaternalBiotypeId;
    }

    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Geolocation getGeolocation() {
        return this.geolocation;
    }
    
    public void setGeolocation(Geolocation geolocation) {
        this.geolocation = geolocation;
    }

    public Biotype getBiotypeByBiotypeId() {
        return this.biotypeByBiotypeId;
    }
    
    public void setBiotypeByBiotypeId(Biotype biotypeByBiotypeId) {
        this.biotypeByBiotypeId = biotypeByBiotypeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Set getIndividuals() {
        return this.individuals;
    }
    
    public void setIndividuals(Set individuals) {
        this.individuals = individuals;
    }

    public Set getStockPhenotypes() {
        return this.stockPhenotypes;
    }
    
    public void setStockPhenotypes(Set stockPhenotypes) {
        this.stockPhenotypes = stockPhenotypes;
    }
   








}