package org.nescent.heliconius.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Synonym generated by MyEclipse - Hibernate Tools
 */

public class Synonym  implements java.io.Serializable {


    // Fields    

     private Integer synonymId;
     private Cvterm cvterm;
     private String name;
     private String synonymSgml;
     private Set featureSynonyms = new HashSet(0);


    // Constructors

    /** default constructor */
    public Synonym() {
    }

	/** minimal constructor */
    public Synonym(Cvterm cvterm, String name, String synonymSgml) {
        this.cvterm = cvterm;
        this.name = name;
        this.synonymSgml = synonymSgml;
    }
    
    /** full constructor */
    public Synonym(Cvterm cvterm, String name, String synonymSgml, Set featureSynonyms) {
        this.cvterm = cvterm;
        this.name = name;
        this.synonymSgml = synonymSgml;
        this.featureSynonyms = featureSynonyms;
    }

   
    // Property accessors

    public Integer getSynonymId() {
        return this.synonymId;
    }
    
    public void setSynonymId(Integer synonymId) {
        this.synonymId = synonymId;
    }

    public Cvterm getCvterm() {
        return this.cvterm;
    }
    
    public void setCvterm(Cvterm cvterm) {
        this.cvterm = cvterm;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSynonymSgml() {
        return this.synonymSgml;
    }
    
    public void setSynonymSgml(String synonymSgml) {
        this.synonymSgml = synonymSgml;
    }

    public Set getFeatureSynonyms() {
        return this.featureSynonyms;
    }
    
    public void setFeatureSynonyms(Set featureSynonyms) {
        this.featureSynonyms = featureSynonyms;
    }
   








}